### ISSUE TITLE
Disable autosave

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#1041]
Would it be possible to add an option to disable autosave when editing a draft article?

We often have to add in HTML within the markdown (for tables etc.), but then if we click on the change editor mode, then click back to the markdown mode, the WYSIWYG editor will have re-worked the HTML that was manually entered within the markdown editor, and then autosaves it, thus losing the hand-crafted HTML.

Whilst a versioning system would be the ideal, in the meanwhile, the ability to turn off autosave would suffice, as it would allow us to reload the article to see the hand-crafted HTML.

Thanks

**Comment by jmduke** [comment]
A versioning system _is_ in the works but this also just sounds like a bug — the goal of the editor is to no-op any content that it can't confidently convert. Can you send an example of content where it's re-writing it?

**Comment by ifpingram** [comment]
Actually, it looks like it might only be stripping formatting whitespace from HTML, as opposed to rewriting HTML. Try adding this snippet into the markdown editor and see what happens when you go to WYSIWYG and back again:

`
<div style="text-align: center; width: 100%;">
    <table style="width: 100%;">
        <thead>
        <tr style="background-color: #6cb8fc;">
            <td colspan="3" style="padding: 8px; text-align: center;">
                <span style="font-family: Arial, Helvetica, sans-serif; font-style: normal; color: #000000; font-weight: bold; font-size : 1.3em;">
                    CSG Pension Income Rates 2023
                </span>
            </td>
        </tr>
        <tr style="background-color: #9bcfff;">
            <td style="padding: 6px; text-align: center;">
                <span style="font-family: Arial, Helvetica, sans-serif; font-style: normal; color: #000000; font-weight: bold; font-size : 1.1em;">
                    CSG Rate
                </span>
            </td>
            <td style="padding: 6px; text-align: center;">
                <span style="font-family: Arial, Helvetica, sans-serif; font-style: normal; color: #000000; font-weight: bold; font-size : 1.1em;">
                    Single Person
                </span>
            </td>
            <td style="padding: 6px; text-align: center;">
                <span style="font-family: Arial, Helvetica, sans-serif; font-style: normal; color: #000000; font-weight: bold; font-size : 1.1em;">
                    Couple
                </span>
            </td>
        </tr>
        </thead>
        <tbody>
        <tr style="background-color: #e0eee0; text-align: center; font-family: Arial, Helvetica, sans-serif; font-style: normal; color: #000000; font-weight: normal; font-size : 1em; padding: 5px;">
            <td>
                0%
            </td>
            <td>
                &lt;€11,614
            </td>
            <td>
                &lt;€17,816
            </td>
        </tr>
        <tr style="background-color: #ffffff; text-align: center; font-family: Arial, Helvetica, sans-serif; font-style: normal; color: #000000; font-weight: normal; font-size : 1em; padding: 5px;">
            <td>
                3.8%
            </td>
            <td>
                &lt;€15,183
            </td>
            <td>
                &lt;€23,291
            </td>
        </tr>
        <tr style="background-color: #e0eee0; text-align: center; font-family: Arial, Helvetica, sans-serif; font-style: normal; color: #000000; font-weight: normal; font-size : 1em; padding: 5px;">
            <td>
                6.6%
            </td>
            <td>
                &lt;€23,564
            </td>
            <td>
                &lt;€36,144
            </td>
        </tr>
        <tr style="background-color: #ffffff; text-align: center; font-family: Arial, Helvetica, sans-serif; font-style: normal; color: #000000; font-weight: normal; font-size : 1em; padding: 5px;">
            <td>
                8.3%
            </td>
            <td>
                &gt;€23,564
            </td>
            <td>
                &gt;€36,144
            </td>
        </tr>
        </tbody>
    </table>
</div>
`
