### ISSUE TITLE
Docs search broken on iOS/iPadOS Safari

### ISSUE THREAD

**Issue by benborgers** [buttondown-email/roadmap#1097]
Typing in the search bar seems to throw up the Next.js “an error has occurred — check the console for more” screen. 

I’m happy to take this and debug with the connected iPhone <> Mac developer console. 

Inspired by: https://secure.helpscout.net/conversation/2132649809/238

**Comment by jmduke** [comment]
@benborgers Yup, please go ahead and take this!
