### ISSUE TITLE
"405 Method Not Allowed" on subscriber import

### ISSUE THREAD

**Issue by chadwhitacre** [buttondown-email/roadmap#11]
# Steps

1. https://buttondown.email/settings/import-subscribers
1. click to upload a CSV
1. upload [test.csv](https://github.com/buttondown-email/roadmap/files/6957197/test.csv)

# Expected

New contacts imported.

# Actual

![unnamed](https://user-images.githubusercontent.com/134455/128769639-83a895cb-6271-454d-b578-a41269a1126d.png)

**Comment by jmduke** [comment]
Yup, got a repro. This is what I get for trying to be clever and roll out a refactor.

**Comment by jmduke** [comment]
@chadwhitacre — fix going live now (should be up in ~15 minutes)!

**Comment by chadwhitacre** [comment]
Confirmed fixed, thanks!
