### ISSUE TITLE
Add ordered lists numbered by letters (a, b, c) to editor

### ISSUE THREAD

**Issue by benborgers** [buttondown-email/roadmap#1158]
Instead of 

```
1. 
2. 
3. 
```

the list would be 

```
a. 
b. 
c.
```

This does look like it’d require digging up the CSS that renders the preview, because it manually appends numbers in the `::before`. 

It’s possible to add `<ol type="a">` in the markdown editor, but switching to the rich text editor and typing anything else causes TipTap to override it. 

From a tiny bit of testing, it seems like at least HEY's email parser requires the corresponding CSS, not just `type="a"`: 

```css
ol { list-style-type: lower-alpha; }
```

**Comment by jmduke** [comment]
WONTFIX
