### ISSUE TITLE
Add templating to confirmation reminder email titles

### ISSUE THREAD

**Issue by antons** [buttondown-email/roadmap#1170]
#1030 worked great in testing, so I assumed that that templating would also work in confirmation reminder titles. It appears that it doesn’t work there, because we just sent a batch of reminders with that ended up with ~1000-character long unprocessed titles.

Would be great if confirmation reminder titles also supported templating.

**Comment by benborgers** [comment]
Sorry about this! We’ve now added support for templating here as well.
