### ISSUE TITLE
UTM source extraction in export stopped working

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#1173]
Since about the beginning of Feb, the extraction of utm_source referrer_url to the utm_source in the export spreadsheet has stopped working. We can see them in the referrerl_url column, but the utm_source column is blank.

Is this perhaps also connected to the fact that in the Subscribers Notes, the Referrer Code is now a random string, and no longer the utm_source of the referrer?

<img width="435" alt="Screenshot 2023-02-17 at 20 32 47" src="https://user-images.githubusercontent.com/1426859/219787505-20afa2d0-f135-4ef5-87f8-4d71ff4fbc76.png">

**Comment by jmduke** [comment]
Fix going live, sorry about that @ifpingram. Do you need me to backfill the missing values from the past few weeks for ya?

**Comment by ifpingram** [comment]
Thanks. Would be nice if you could please as the excel formula I need to work it out otherwise is a little convoluted.

Cheers!

**Comment by jmduke** [comment]
@ifpingram Just kicked it off; they should be backfilled in the next hour or so.

**Comment by ifpingram** [comment]
Thanks. I can confirm that all is now correct.
