### ISSUE TITLE
preview render hides two bottom lines behind toolbar

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#1192]
![image](https://user-images.githubusercontent.com/89615/221056239-d1e45783-2f1d-42ef-892e-545538758e35.png)
Expected: I don't want any text to be hidden by the UI
Actual: There are two lines behind the toolbar

I see that if I text-focus in the editor, this toolbar goes semi-transparent, somewhat ameliorating this problem. But I've found myself cursing this (fairly new) visual arrangement already, wishing that I could scroll down farther to see all my rendered text.

Ideally, I'd like to be able to scroll up-to-another-page's worth so I don't have to look at the very bottom of my screen all the time.

**Comment by jmduke** [comment]
@benborgers Mind poking around on this one?

**Comment by james-baker** [comment]
Thanks for the `padding-bottom: 9rem` I now see there! Gets the text away from the bar easily, and I don't have to be looking at the verrry bottom of the screen all the time (the way I do in the markdown editor pane).

**Comment by benborgers** [comment]
@james-baker Great! To clarify — is there not enough padding in the markdown editor as well?

**Comment by james-baker** [comment]
Naw, there's "enough" to see the bottom line of text. (Since the bottom of the editor is above the toolbar, in contrast with the preview pane.) You just can't scroll any farther; word processors usually give you some extra margin there too

**Comment by benborgers** [comment]
There should be some added extra margin now!
