### ISSUE TITLE
adding subscribers - do they get welcome email or not?

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#1194]
I notice a redesigned "create new subscriber" dialog design.
I notice the checkbox re "send them welcome emails or not" has disappeared.

So... do they get the welcome email, like self-subscribed people? Or not?

Expected: ability to send welcome emails automatically to admin-created subscribers
Expected: ability to know what experience my new subscriber will have when I use this dialog

**Comment by jmduke** [comment]
This is a (temporary) regression; there's some weird non-deterministic behavior here so I added a clientside flag to hide it! They will _not_ be receiving emails atm but keeping this open to track when it's fixed.

**Comment by james-baker** [comment]
Do I see that this is resolved by a setting on the Settings page now?

**Comment by jmduke** [comment]
Indeed!
