### ISSUE TITLE
New message editor text (markdown) disappears and has to be replaced (though preview shows proper text)

### ISSUE THREAD

**Issue by WyrdByWord** [buttondown-email/roadmap#1242]
This happens to me routinely:

1. I use the New Mail button to open an editor window. I am using the Markdown editor.
2. I paste the subject line in
3. I paste the message text 
4. The message preview renders and then the message text disappears (the preview windows remains populated)
5. I paste the text in again and everything works as expected

**Comment by jmduke** [comment]
@benborgers Mind taking a look at this?

**Comment by benborgers** [comment]
Thanks for reporting this @WyrdByWord! Could you by any chance get a screen recording of this happening? I can’t seem to reproduce it, unfortunately: 

https://share.cleanshot.com/823tlssK

Am I perhaps doing something differently in the process that’s causing the issue not to happen?

**Comment by WyrdByWord** [comment]
After further investigation, I think this is an issue on my end. Still trying to figure out what it is. Sorry for the trouble!

**Comment by benborgers** [comment]
No worries at all! I appreciate you reporting it. Please reopen this if it ends up looking like an issue with Buttondown!
