### ISSUE TITLE
Refresh documentation on scheduling emails

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#1307]

**Comment by jmduke** [comment]
@madelinezday looks great: a couple tiny comments but feel free to transpose. (This also might be a good easy candidate for a ~two minute screencast!)

**Comment by madelinezday** [comment]
https://github.com/madelinezday/buttondown/blob/scheduling/scheduling-email.md

^^ Here's the finished markdown! Also just created a checklist item for practicing with a short voiceover.
