### ISSUE TITLE
Document author-facing referrals

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#1308]

**Comment by madelinezday** [comment]
Google doc is ready for review here!

https://docs.google.com/document/d/1Q1TmsBBNBly7R3789gdmvkNxx6aqo6rDhhav5Y4j4MQ/edit?usp=sharing

Just one question towards the end re: sending remittances!

**Comment by jmduke** [comment]
@madelinezday Couple small comments, great overall!

**Comment by madelinezday** [comment]
Here's the completed Markdown file—let me know if you have any additional edits!!

https://github.com/madelinezday/buttondown/blob/main/guides/referrals.md

**Comment by jmduke** [comment]
Amazing! Will get this published this evening.
