### ISSUE TITLE
Document using teams

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#1309]

**Comment by madelinezday** [comment]
Here's the first draft! I have two (hopefully) quick questions in the comments, too!

https://docs.google.com/document/d/1sX17CR-KMttU9EW4WWVMt2oNimg5zxQGG8h89e3wWtI/edit?usp=sharing

**Comment by madelinezday** [comment]
Here's the final Markdown doc! Let me know if you have any additional edits—happy to implement them!

https://github.com/madelinezday/buttondown/blob/main/guides/teams.md
