### ISSUE TITLE
Add documentation for writing + sending surveys

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#1317]

**Comment by jmduke** [comment]
https://www.loom.com/share/ebc0182fce694bd38cb90f679c64da93

**Comment by madelinezday** [comment]
This is in progress, but just wanted to say thank you again for the Loom video! This is incredibly helpful!

**Comment by madelinezday** [comment]
Here's the link to the Google Doc for your review!!

https://docs.google.com/document/d/1Va1FTPMNm3MRaPyRhKktJVyhF4zx8P9z3faRWpxF0Ms/edit?usp=sharing

I'll go through once more to proofread for little things as well, just since this one ended up being pretty long!

**Comment by jmduke** [comment]
Excellent work as always; small comments, feel free to transpose right
after you address them. I’m at a conference today + tomorrow but will try
and make sure you have a couple more in the hopper by tomorrow!

—
Justin Duke
Founder, Buttondown

**Comment by madelinezday** [comment]
Here's the finished Markdown doc!! And have fun at your conference!!

https://github.com/madelinezday/buttondown/blob/main/guides/surveys.md
