### ISSUE TITLE
Template tags not working in plain text emails

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#133]
Look at `spreddo`'s account for an example

**Comment by rghedin** [comment]
I was tinkering with plain text emails and noticed that special tags in Design panel, such as {{ unsubscribe_url }}, don't render on sent messages.

<img width="536" alt="Captura de Tela 2021-12-23 às 12 17 42" src="https://user-images.githubusercontent.com/19216581/147259789-0ff4ad0d-e24f-468a-9841-3a9cf1286cba.png">

<img width="396" alt="Captura de Tela 2021-12-23 às 12 17 51" src="https://user-images.githubusercontent.com/19216581/147259821-e4407b33-7584-443c-ae08-542eae9b516e.png">

Also, line breaks is very inconsistent on templating/designing. Sometimes they don't work, but if I add double space in their end (like in Markdown), it works.
