### ISSUE TITLE
Clear out slug when duplicating email

### ISSUE THREAD

**Issue by benborgers** [buttondown-email/roadmap#1370]
When duplicating an email, the resulting email has the same slug as the first. Changing the subject line of the email and not realizing this results in a new subject with the last email’s slug. 

It’d be nice to clear that slug when duplicating an email so that it can match the new subject. 

https://secure.helpscout.net/conversation/2210945522/677

**Comment by jmduke** [comment]
You duped yourself! Closing in favor of https://github.com/buttondown-email/roadmap/issues/1220.

**Comment by benborgers** [comment]
Wow this really confirms that I always phrase things in a particular way - thanks for catching!
