### ISSUE TITLE
Bulleted lists are huge in archive rendering

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#139]
Repro:
Go to an archive newsletter page that contains a bulleted list, like https://buttondown.email/intentionalsociety/archive/intentional-society-season-transition/

Expected: Rendered style/CSS matches email
Actual: The text in the bulleted list is huge

These bits of text should be the same size:
![image](https://user-images.githubusercontent.com/89615/135693757-8277da6e-58bd-4503-8dec-ef9118d26af4.png)

The cause looks to be in base.scss:538
p,label,li{
  font-size:1.45em;
  line-height:1.3em
}
and the html structure is that each &lt;li> has a &lt;p> inside of it, and did you know that "em" units are relative to the size of their parents? I sure forgot.

P.S. I like the upgrades to the archive newsletter styling overall! The blue header, big title, improved subscribe/social at the bottom, etc.

**Comment by jmduke** [comment]
Thank you for the extremely meticulous bug report (& sleuthing on your own!)

Agreed; this is a trivial fix. Will get something out either today or tomorrow.

**Comment by jmduke** [comment]
Merge going live now!
