### ISSUE TITLE
Changing slug and then sending an email shows old slug

### ISSUE THREAD

**Issue by benborgers** [buttondown-email/roadmap#1407]
If you edit the slug of an email and then schedule it, etc., the confirmation modal shows the wrong slug. 

It looks like this is happening because the modal shows `absolute_url`, which is a backend-calculated value. Since only the `slug` property has been updated on the frontend, `absolute_url` hasn’t been re-evaluated. 

https://secure.helpscout.net/conversation/2210945522/677

**Comment by james-baker** [comment]
This regularly gives me a small freakout, and I would appreciate if it were fixed.

"Oh no this url is bad. I just fixed/changed that - did I not hit save? etc" when seeing the now-publishing dialog come up.

**Comment by jmduke** [comment]
@james-baker Missed this — and thanks for the preliminary sleuthing @benborgers. Will fix tomorrow a.m.!
