### ISSUE TITLE
Search results: Subscriber status

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#1423]
Would be good if the subscription status of the Subscriber could also be listed on the search results page please:

<img width="326" alt="Screenshot 2023-04-19 at 08 30 59" src="https://user-images.githubusercontent.com/1426859/233001795-0a0a2d1a-041f-489a-879d-24c0d2e2fb91.png">

The top one is a Premium, the others are not. Would be nice to be able to differentiate at this point please.

Thanks!

**Comment by jmduke** [comment]
Our path forward for this should/will be: use the exact specific row type for each group of search result, and allow selection and full row therein.

**Comment by ifpingram** [comment]
Nice - that works really well. Thanks!
