### ISSUE TITLE
Urgent - "Teaser" email test not rendering Markdown image

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#1445]
Trying to test a "Teaser" email ID 693ffe26-cdae-49b1-979d-e8688214e904, the contents of which start:

```
![](https://buttondown.imgix.net/images/77c86ff6-2fef-40c2-b894-24169ec0f026.jpg?w=960&fit=max)

## <span style="color: #0033cc">French Residence Permit Process ‘Deficient’</span>

 

<p><span style="color: #3366ff">27th April 2023</span></p>
```

However, when we send ourselves the test, the Markdown image is not rendered and instead it closes up all the new lines, and instead gives us the following in the test email:

```
![](https://buttondown.imgix.net/images/9a513910-47a1-4038-bff1-59d03021172d.jpg?w=960&fit=max) . ## French Residence Permit Process ‘Deficient’  
27th April 2023
```

We're looking to send this teaser quite urgently, so would be really grateful if could be fixed soon please.

Thanks!

**Comment by jmduke** [comment]
Taking a look.

**Comment by jmduke** [comment]
Ah, I see what the error is. It'll take me some time to get a fix out, but in the meantime I've replaced the custom teaser you're using with the rendered HTML which should now fix the issue.

**Comment by ifpingram** [comment]
Many thanks Justin. I'm such an idiot - I didn't think of doing that!
