### ISSUE TITLE
Ability to change subscriber email

### ISSUE THREAD

**Issue by benborgers** [buttondown-email/roadmap#1540]
May have been a feature before, but lost in migrations? 

Example: https://secure.helpscout.net/conversation/2256479683/902

**Comment by james-baker** [comment]
+1 yes please - having to unsubscribe and resubscribe a subscriber makes it really hard to track history across the two different userIDs, have to migrate the tags and metadata manually, plus it's just a messy/bad experience for the end user too.

I think this was possible on the older Notes modal at some point.

**Comment by jmduke** [comment]
@james-baker It was indeed possible in the previous iteration, and as penance for being extremely slow with the other bug you flagged a while back I’ll bump this up to make sure it gets taken care of early next week.

**Comment by james-baker** [comment]
Hah, no particular rush but I appreciate the sentiment :)
