### ISSUE TITLE
Enforce integerial timing delays in automations

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#1557]
Right now, someone can specify `hours=0.5`, which breaks on the backend. cc @JesperDramsch — looks like you've got a couple of these that I'm just moving over to 30 minutes instead

**Comment by jmduke** [comment]
(Ah, and we need to specify minutes clientside — will do that too.)

**Comment by JesperDramsch** [comment]
hehehe, I was wondering if I'd break anything with this.
