### ISSUE TITLE
Link checker has an issue with perfectly normal twitter link

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#1610]
This triggered the link-checker today. I double-checked it, with and without a "www":

https://twitter.com/vgr/status/1073751685212692480

Expected: this should look good (and load, assuming it's trying to validate by fetching something) to the link checker

**Comment by jmduke** [comment]
Yup, seeing this as well. I suspect it's Twitter whining for an anti-scraping measure.
