### ISSUE TITLE
Allow setting metadata in the CreateSubscriberModal

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#163]

**Comment by james-baker** [comment]
I went looking for this feature today. The idea was to be able to use a metadata.firstname template variable to personalize the welcome (included on subscription) issue of the newsletter. By the time the subscriber has been created and I can edit their metadata, the welcome-to-subscription email has already gone out, I presume.

If I create a subscriber with metadata via the API, will that personalized-welcome use case work?

**Comment by jmduke** [comment]
Yes, it will! Thanks for the bump here, though — I may be able to hammer this out this week.
