### ISSUE TITLE
Link color in emails is too dark in dark mode

### ISSUE THREAD

**Issue by benborgers** [buttondown-email/roadmap#1644]
In some email clients (Windows, Thunderbird), or perhaps more than just some, the default blue color for links is too dark against a dark background to be easily readable. 

https://secure.helpscout.net/conversation/2287619532/1038

**Comment by jmduke** [comment]
@benborgers is this still a thing?

**Comment by benborgers** [comment]
It hasn't resurfaced, so I think we'll close this in favor of it perhaps coming back up in the Modern template.
