### ISSUE TITLE
"Opened" analytic count appears to be inaccurate

### ISSUE THREAD

**Issue by dakrone** [buttondown-email/roadmap#1651]
Here's an example of a recent email analytics page:
<img width="757" alt="Screenshot 2023-07-08 at 9 08 19 PM" src="https://github.com/buttondown-email/roadmap/assets/19060/6d944772-6a1d-4e04-b3ec-a3ab6a30c9fd">

Despite being opened by 13 distinct email addresses, the open count shows as 4

**Comment by jmduke** [comment]
Looks like the analytics caching is overly aggressive. Thanks for the flag; will work on improving this early this coming week.
