### ISSUE TITLE
Buttondown's home page has no "login" button on mobile browser

### ISSUE THREAD

**Issue by dakrone** [buttondown-email/roadmap#1652]
When I browse to https://buttondown.email on my mobile device, the "Login" page normally present on the page is missing. The only way I have been able to log in to buttondown from my phone is to go directly to https://buttondown.email/login

Would it be possible to put a link to the login page from the home page that shows up for mobile users?

**Comment by jmduke** [comment]
Absolutely. Going live in an hour.
