### ISSUE TITLE
Caching backfill did not finish

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#1707]
![image](https://github.com/buttondown-email/roadmap/assets/89615/3754eca8-1287-4961-9b79-869feabb069b)

I've turned on the display of "Opens" and "Open rate" via the little "+" column-selector-menu.

Expected: All of these rows are populated with numbers/percentages
Actual: about 40% of all rows display big dashes instead of the stats.

The stats seem to be there and exist: I can see them, one by one, by pulling up the "Analytics" modal for a specific email. The numbers are very normal-looking, too - not like outliers are being excluded.

**Comment by jmduke** [comment]
Sounds like the cacher is... awry. Will take a look at this tomorrow morning.

**Comment by jmduke** [comment]
Looks like this was a problem with the initial backfill, and not the ongoing cacher (thus the issue rename). Kicked off a new one so these should be appearing shortly.

**Comment by james-baker** [comment]
The backfill (on my main newsletter, at least) now looks complete. Still lots of dashes on a secondary newsletter.
