### ISSUE TITLE
Opens data incorrectness?

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#1752]
This seems wrong/inconsistent in some way, though I'm not sure how to interpret it:

![image](https://github.com/buttondown-email/roadmap/assets/89615/703549c2-36e5-421b-a1d4-45a1cc507164)
(On an email sent 6 days ago, says 12 opens, then expands into a list of 19 emails that have opened it one or more times.)

Checking two weeks ago... yep inconsistent there too: says 12 opens, lists 16 emails.
Oh 3 weeks ago (when I sent this newsletter to more tags/people) it says 18 opens, lists 42 emails.

But I checked some that are a month or more older, and those all seem accurate in my limited sampling.

On the inconsistent analytics, the top-line opens count seems abnormally low on some recent emails compared to historical averages, so I think maybe I trust the detailed email list more? (Hmm, how long ago was the "cacher" introduced?)

**Comment by jmduke** [comment]
[grumbles about caching]

I think I need to take a further stab at caching — I suspect what's happening here is its prematurely and then not updating when folks open/interact with emails after the fact.

**Comment by james-baker** [comment]
Any updates? I haven't found any easy way to get at the real open rate for the last five weeks now:
![image](https://github.com/buttondown-email/roadmap/assets/89615/b587d30e-bb53-4430-9d62-38ed28c0e326)

I can roughly scroll-page through the detailed list of opens to get an estimate, which tells me that no nothing awful is happening and people are still opening my newsletter at much higher rates than are reported.

**Comment by jmduke** [comment]
Alas, no — though not for lack of trying. I'm still poking around specifics here, but thanks for the bump.

**Comment by jmduke** [comment]
@james-baker I _believe_ I've finally root-caused this! Do you mind re-opening if you see any subsequent emails run though this issue?

**Comment by james-baker** [comment]
Thanks, will do, and/but does that mean the percentages on existing emails will not be fixed?

**Comment by jmduke** [comment]
@james-baker They're slowly getting backfilled, but I'll manually run it for the secondary for ya this afternoon.

**Comment by james-baker** [comment]
Oh I wondered if it was a long-running process. Verified, all fixed for me.
