### ISSUE TITLE
Make Zapier/API access for adding subscribers free

### ISSUE THREAD

**Issue by benborgers** [buttondown-email/roadmap#1776]
This would allow people who don't have a paid plan to continue collecting subscribers via Zapier and API, bringing it in line with the built-in subscribe forms and endpoint. 

https://secure.helpscout.net/conversation/2320748067/1211

**Comment by bdwhitebd** [comment]
Any updates on a potential ETA for this feature?

**Comment by jmduke** [comment]
Thank you for the poke; I will ship this tomorrow.

**Comment by bdwhitebd** [comment]
Amazing!

**Comment by jmduke** [comment]
@bdwhitebd Going live now!
