### ISSUE TITLE
Erroneous wording on Unsubscribe and Ban for subscribers

### ISSUE THREAD

**Issue by benborgers** [buttondown-email/roadmap#1790]
Is it true that, once unsubscribed, someone can't subscribe again? 

<img width="607" alt="2023-08-09 at 14 20 13@2x" src="https://github.com/buttondown-email/roadmap/assets/30215449/359e49df-f364-4535-a1b9-4dfc6b5d2ec1">

This seems like it's the copy for Ban and Delete together:

<img width="603" alt="2023-08-09 at 14 20 07@2x" src="https://github.com/buttondown-email/roadmap/assets/30215449/a4c3432a-eef6-427b-ac13-a6b08f6978d1">

**Comment by jmduke** [comment]
Nope! Thanks for the catch there. We should fix the copy
