### ISSUE TITLE
Inter font is missing and defaulting back to Times New Roman 

### ISSUE THREAD

**Issue by benborgers** [buttondown-email/roadmap#1867]
I _think_ the fix is just to deploy the Buttondown app on Heroku again — there's a commit on `main` for loading the font from Google Fonts but it didn't deploy. 

Although I'm still a bit confused about why the old font files aren't still working if that commit never deployed? 

https://secure.helpscout.net/conversation/2348981619/1385

**Comment by jmduke** [comment]
Yup. Closing this.
