### ISSUE TITLE
Clicking "emails" in sidebar should reset filters

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#1879]
![image](https://github.com/buttondown-email/roadmap/assets/89615/6fd71903-1e08-4ee0-b591-dfa79ee39a7a)

If I've messed around with filtering a bunch
and I just want to reset the page
my instinct is to click "Emails" on the sidebar
this instinct is affirmed by seeing a URL with all the filtering params gone

Expected: this click should reset the filters, and be like "load a fresh page"
Actual: the URL changes to drop all the filter params, but the UI doesn't clear the filters

alternate expectation: the click should do nothing, meaning it shouldn't change the URL or the filters

**Comment by jmduke** [comment]
👍 totally makes sense, agreed.

**Comment by james-baker** [comment]
👍🏻 P.S. I also just discovered that All/Drafts/Sent in the top-right UI are buttons, not just static readouts :headdesk:
