### ISSUE TITLE
silent 400 trying to change (reconcile across multiple newsletters) subscriber's email address

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#1940]
Subscriber A is on newsletter 1 and newsletter 2, with different addresses. They want to use only one address, the one on N1.
Repro:
Go to N2, user Notes/detail page for A.
From triple-dot menu, "Change email address"
Enter the email address in the simple browser form.

Expected 1: Error message, if something is wrong
Actual 1: Silent failure

Expected 2: No error
Actual 2: In the console, I see a 400 on the PATCH request, with     "code": "email_already_exists",    "detail": "Email address <REDACTED> already exists.",

Yes this email address already exists, that is the point - but it only exists in the subscriber list of N1, not N2.

There shouldn't be any complicated merging of subscribers required to allow this, right? Separate subscriber lists for each newsletter, was the model in my head.

**Comment by jmduke** [comment]
@james-baker Can you DM / email me what the specific N1 and N2 are? I suspect that what was happening is that subscriber A did already have their new address on N2 but perhaps in a deactivated/unsubbed condition; we don't do any cross-newsletter checking here.

**Comment by jmduke** [comment]
NARRATOR: There was, in fact, a cross-newsletter check. (t/y for details @james-baker). Trivial fix but will have to wait a bit as I'm traveling this weekend + coming week; you should be able to delete + recreate that subscriber with the new email as a workaround.

**Comment by jmduke** [comment]
Fix rolling live!
