### ISSUE TITLE
Subscriber detail page automations could show time as well

### ISSUE THREAD

**Issue by benborgers** [buttondown-email/roadmap#1952]
![image](https://github.com/buttondown-email/roadmap/assets/30215449/4b62d7ad-1094-40b2-ad7c-bd4934aeaf71)

Since automations are more granular, it could be useful to include a timestamp with the date on this card of the subscriber detail page. 

https://secure.helpscout.net/conversation/2385793712/1641

**Comment by thinkplaymake** [comment]
this is super helpful especially when implementing/debugging automations at the start, but also to see how recently an automation happened, if someone is complaining they didn't receive an email yet :)
