### ISSUE TITLE
Code blocks don't look good in Mail.app dark mode

### ISSUE THREAD

**Issue by benborgers** [buttondown-email/roadmap#1970]
![image](https://github.com/buttondown-email/roadmap/assets/30215449/9d0f7703-43c9-49c8-9fee-ea2bf3d76ce7)

https://secure.helpscout.net/conversation/2392866434/1698

**Comment by jmduke** [comment]
Closing in favor of https://github.com/buttondown-email/roadmap/issues/1053.
