### ISSUE TITLE
Text is being lost in RSS-to-email around backticks

### ISSUE THREAD

**Issue by benborgers** [buttondown-email/roadmap#1981]
| | |
| --- | --- |
| ![Screenshot_20231021-100548_K-9_Mail](https://github.com/buttondown-email/roadmap/assets/30215449/db6e5859-520a-4a80-8e86-648094eeaf39) | ![Screenshot_20231021-100558_Firefox](https://github.com/buttondown-email/roadmap/assets/30215449/d278c591-71b6-4f89-a477-f3e552efc7b2) |

https://secure.helpscout.net/conversation/2396471610/1720

**Comment by timabell** [comment]
https://buttondown.email/tim_abell/archive/

https://timwise.co.uk/2023/10/20/git-what-do-'base'-'local'-'remote'-mean/

**Comment by jmduke** [comment]
Fix rolling live right now.
