### ISSUE TITLE
Scheduled Emails section should display both the date and time of the scheduling

### ISSUE THREAD

**Issue by martindufort** [buttondown-email/roadmap#20]
Would allow us to better know when things are going out without having to <reschedule and cancel>
![CleanShot 2021-08-17 at 15 35 26@2x](https://user-images.githubusercontent.com/28934641/129789514-6e2f4bc1-c27e-4bbb-a518-a85c89fe1db6.png)

**Comment by jmduke** [comment]
@martindufort Have you tried changing the 'date format' under design? I think that should cover this case.
