### ISSUE TITLE
Don't offer clicks or replies as automation trigger options if the relevant tracking isn't there

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#2012]
Folks have to explicitly opt into click or open tracking (`Newsletter.should_track_replies`, `Newsletter.should_track_clicks_on_emails`.) However, we currently have a bug: someone can _not_ opt into these tracking but create automations that rely on them as triggers!  We should hide or disable those triggers (which are in `assets/screens/Sequences/lib`) and add a regression test to make sure this doesn't happen.

This should be pretty simple _because_ we already have a mechanism for hiding certain triggers; check out the `isRelevantTrigger` method in that same file. All we need to do is expand that to also take the newsletter as an argument.

**Comment by tanvirraj** [comment]
@jmduke we can close this one now.
