### ISSUE TITLE
`customer_created` fails if the email address used fails out

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#2041]

**Comment by jmduke** [comment]
https://buttondown-email.sentry.io/issues/4619541994/?project=213773&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+none%5D&referrer=issue-stream&sort=inbox&statsPeriod=14d&stream_index=2

**Comment by tanvirraj** [comment]
seems like this issue has same problem #2191  https://github.com/buttondown-email/roadmap/issues/2191
