### ISSUE TITLE
Breadcrumb in `FeaturePage` should be clickable

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#2058]

**Comment by jmduke** [comment]
The thing that says "Stories" here:



![Image](https://github.com/buttondown-email/roadmap/assets/461046/2e65c523-55c7-43f9-95a8-bb5b05184446)


It's got a couple different possible values (which we should reify into a typescript type!) and they should all link back to the parent page.

**Comment by zeucapua** [comment]
When you mean "link back to the parent page", does that mean the "/" index page, or should I create pages for each of the possible breadcrumbs, similar to `/features` page. If so, I would need to make: 'stories/customers', 'behind the scenes (/open source, /stack, etc)', 'comparison guides', etc. to link to.

**Comment by jmduke** [comment]
For anything that doesn't have a natural top-level page, just link back to Index! (And for customer stories, that can just go to `/blog`)
