### ISSUE TITLE
Redirect inbound email sent to Sending Domain

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#2077]
Hi Justin

Hope you are well.

Do you have a way to forward emails sent to the email address from which we send the emails please? We send from editor@newsletter.france-insider.com and have a sending domain of newsletter.france-insider.com, but the problem we face is that if somebody sends a reply to the newsletter they receive, it bounces. 

We do not have any MX records set up for this email address, but were perhaps wondering if you had a redirect in place for SMTP received as mail should try to land where we have pointed the A records of newsletter.france-insider.com to, which is your servers.

If nothing available for a redirect your side, then I will look at setting up MX records and handling it ourselves. You should probably put a note about this in the Sending Email and Sending Domain config in Buttondown, so people don't overlook it like we have for so long.

Thanks!

**Comment by jmduke** [comment]
@ifpingram Turn on reply tracking (under tracking, in settings!) That replaces the default sending email with Buttondown's and it'll redirect any replies to your account's email.

**Comment by ifpingram** [comment]
Many thanks! 

I have tried to give it a go, and I get the following error:

<img width="341" alt="Screenshot 2023-11-21 at 21 15 00" src="https://github.com/buttondown-email/roadmap/assets/1426859/65f7622a-9206-4720-b9bc-80409023a0ca">

Any clues?

Thanks

**Comment by jmduke** [comment]
@ifpingram Ugh sorry about that; mind trying again?
