### ISSUE TITLE
Filter by "not tag"

### ISSUE THREAD

**Issue by benborgers** [buttondown-email/roadmap#2103]
Currently you can filter by tags on the Subscribers view, this would be adding another state where it’s filtered by _not_ that tag. 

(This could get a bit intuitively tricky because currently the tags are OR’d together but OR-ing a NOT "tag" _may or may not be_ what one would expect?)

https://secure.helpscout.net/conversation/2432266550/1948

**Comment by jmduke** [comment]
Closing as dupe of https://github.com/buttondown-email/roadmap/issues/884.
