### ISSUE TITLE
Gmail + Yahoo bulk mail updates

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#2306]
Hi Justin

I've received the below from AWS. No doubt you've already got this in hand, should it affect Buttondown, but in case if not:

==

Hello,

In a move to safeguard user inboxes, Gmail [1] and Yahoo Mail [2] announced a new set of requirements for senders. Effective February 2024, the new requirements affect email senders who distribute over 5,000 bulk messages per day or have >0.3% of messages reported as spam. Failure to comply with the new requirements may result in Gmail and Yahoo rejecting message delivery to their customers.

For more information on the new mailbox provider requirements and how to comply, please visit the AWS blog [3]. If you have any questions or concerns, please reach out to AWS Support [4].

[1] https://blog.google/products/gmail/gmail-security-authentication-spam-protection/
[2] https://blog.postmaster.yahooinc.com/post/730172167494483968/more-secure-less-spam
[3] https://aws.amazon.com/blogs/messaging-and-targeting/an-overview-of-bulk-sender-changes-at-yahoo-gmail/
[4] https://aws.amazon.com/support

Sincerely,
Amazon Web Services

**Comment by jmduke** [comment]
No action necessary! :)

**Comment by ifpingram** [comment]
Perfect thanks
