### ISSUE TITLE
cursor jumps to bottom while editing

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#2323]
Experiencing this last night and this morning.

Repro: Normal new email editing flow
Click up into an already-written part and write some more.

Expected: undisrupted editing experience
Actual: several times, the edit cursor jumps (seemingly related to some background saving) all the way down to the bottom. I notice it after a couple words, and it's a mess to delete there and go back up again. This wasn't happening reliably every few seconds after typing, it was more like once a minute ish.

Also (but only once) I had my last four words disappear after a quick-save, when I was typing at the bottom of the doc. Similar to the way that editing titles is annoyingly unreliable.
I also experienced #2292 soon after, might not be related.

**Comment by james-baker** [comment]
I did *not* experience this today that I'm aware of. (But, I also wrote my newsletter very sequentially and didn't jump back up to edit much.)

**Comment by jmduke** [comment]
I am gonna close this one out as I believe I fixed the bug (it was an overzealous draft-syncer.)
