### ISSUE TITLE
Access to `subscriber.id` or `subscriber.metadata.id` in template variables

### ISSUE THREAD

**Issue by zachleat** [buttondown-email/roadmap#2458]
Howdy I’d love to be able to access the subscriber primary key (or id) in my template variables!

https://docs.buttondown.email/odds-and-ends/template-variables

Example:

```
[redeem now](https://conf.11ty.dev/tickets/{{subscriber.metadata.id}})!
```

Thanks!

**Comment by jmduke** [comment]
@zachleat Going live in ten minutes!
