### ISSUE TITLE
Allow subscriber removal to skip-or-undo permanent ban

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#256]
Minimal envisioned implementation: Extra button on the "delete subscriber" modal, such that the buttons are roughly:
* Cancel
* Remove/Unsubscribe
* Ban/Delete
with text in the modal explaining that "removed subscribers can re-subscribe, while banned subscribers cannot"

Alternate/larger implementation: Make deleted/banned subscribers visible in a table/list, and editable to cease blocking them.

Motivation: Newsletter owners currently cannot simply unsubscribe someone in a way equivalent to them hitting their "unsubscribe" link. "Sorry, I can't unsubscribe you without banning you, please do it yourself" is embarrassing to have to say to a subscriber who wants to take a break.

Motivation 2: Testing the new-subscriber welcome flow without having to increment the test email alias each time

Motivation 3 (larger implementation only): Ability to end someone's ban without emailing Justin to do it. :)

**Comment by jmduke** [comment]
Agree wrt functionality but I'd prefer to have this be two separate modals, just to make each modal conceptually a little simpler!

**Comment by james-baker** [comment]
Yes yes, however is best, implementation ideas only for idea-transmission. :)

**Comment by james-baker** [comment]
Yeah, having this "unsubscribe" option would mean their subscriber record would go into the unsubscribed list and their event history would be preserved, which would be nice.

**Comment by jmduke** [comment]
This is _also_ going live shortly.
