### ISSUE TITLE
misleading UI description of behavior of private archives

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#257]
The "by prohibiting public signup" option on the settings/subscribing page currently reads "your archives are not published to the internet".

I find that this is true for "the archives page" which has a note about the archive being private - but that "not published to the internet" is not true in that each issue is still publicly available at its usual title-based URL after publishing.

I can live with this behavior (ultimately you're trusting your subscribers anyway not to wantonly forward or publish their emails), but seems like the docs could be improved.

**Comment by james-baker** [comment]
Wait a second, there's another setting that purports to hide the issues from the web, but it doesn't do what it says.

On the main /settings page for a newsletter:
"Would you like to allow readers to view an archive of your emails?
If enabled, Buttondown exposes a public archive at https://buttondown.email/is-allies/archive as well as specific links for individual emails, so folks can read and share without using email specifically. You can disable this if you want your newsletter only accessible in email inboxes and not over the web."

This rises to defect level because of the part, "specific links for individual emails".
Expected: When disabled, Buttondown makes the individual emails "only accessible in email inboxes and not over the web" -- and yet
Actual: https://buttondown.email/is-allies/archive/is-allies-welcome-message/ is still accessible from a clean browser

So does the functionality for disabling the "allow readers to view an archive" setting need to be fixed to reflect the text?
And since that setting exists on its own, why does the "prohibiting public signup" subscribing-setting say anything about the archives at all?

**Comment by jmduke** [comment]
Yup, I think you're exactly right here. This second part is a bug. Really there should be three separate permissions-ing tiers:

- subscription over the web
- viewing all archives over the web
- viewing _specific_ archives over the web (if you have a link)

Shifting the label here.
