### ISSUE TITLE
Sending new subscribers latest-or-specific issue not possible for invite-only newsletters

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#258]
My settings:
![image](https://user-images.githubusercontent.com/89615/141879965-ff90f970-5eeb-47da-b7dd-376121e624fa.png)

Result after adding subscriber:
![image](https://user-images.githubusercontent.com/89615/141879901-e5e745ae-3566-4060-8772-c57c8b496952.png)

Expected: the content of that selected archive message should be in the welcome email
Actual: the content of the welcome message seems unchanged from when "...a specific email from my archives." was unchecked.

Tried this with "I'D LIKE TO CUSTOMIZE MY WELCOME EMAIL ...by modifying the welcome message in the email." option both on and off, and that didn't seem to work either - the customized welcome message didn't change the body of the default welcome mail. The "modify the subject" option DOES work, I have confirmed.

**Comment by james-baker** [comment]
Oh, sending the latest email doesn't appear to work either. This escalates the urgency for me.

**Comment by james-baker** [comment]
And if I uncheck "...a welcome email confirming that they've signed up successfully." while still leaving "...the latest email in my newsletter" checked, then nothing seems to get sent at all.

**Comment by james-baker** [comment]
Shoot, this isn't a multi-tenancy issue: it's happening on my main newsletter too! The latest issue is not being sent to new subscribers! yikes

**Comment by jmduke** [comment]
Oh no! Taking a further look right now..

**Comment by jmduke** [comment]
Mind sharing how you're getting that? I just tried subscribing to your main newsletter and am receiving the `Intentional Society: Overlap of object and meta` emails!

**Comment by james-baker** [comment]
Huh....... okay so I'm using "Add" on the subscribers page (by necessity on the 2nd newsletter since it's private, but I suppose that's a different code path than a self-service sign-up)

The entirety of the welcome email I'm getting is:
Thanks for subscribing to Intentional Society Updates! It's great to have you on board.

If you don't see issues of Intentional Society Updates in your inbox, be sure to check:

Your Promotions tab, if you're using Gmail
Your spam folder
Thanks again for subscribing!


...and my recollection (I swear I've seen this work earlier) is that this "You've subscribed" email should contain the text of that latest issue inside the body of that email, right?

**Comment by jmduke** [comment]
Aha! _That's_ why — the latest email deliberately does not send for 'inorganic' subscriptions (meaning subscribers added by the author themselves.) I should have been clued in by the fact that your second newsletter is invite-only. 

I think that behavior makes sense as a default, but it's unintuitive; how does adding an optional checkmark to send the latest email (basically to behave 'normally') to that subscriber creation modal sound?

**Comment by james-baker** [comment]
Hmm - I'll say I'm confused by that default. Given the subscriber settings page, I wouldn't have expected who/how they subscribe to affect the new user flow. If anything I would expect "sneaky add, bypassing the regular flow" to be the exceptional case.

But yes @jmduke , a "do the normal thing" checkbox in the modal would work. Thanks!

**Comment by james-baker** [comment]
and there's no way to manually send an issue to a single subscriber, is there? (In the UI. I saw a beta API that might) So, I guess my workaround for the moment to get this newsletter launched is to load as many in the first batch as possible, then hit send on a new-issue-to-all-subscribers, and then after that, manually send further subscribers a welcome mail from my regular personal email.

**Comment by jmduke** [comment]
There isn't, though I've been meaning to add that! Let me cut a separate feature.

**Comment by jmduke** [comment]
(And I'll try to get this specific feature landed tomorrow.)

**Comment by jmduke** [comment]
https://github.com/buttondown-email/roadmap/issues/280
