### ISSUE TITLE
Cannot uncheck "...by modifying the welcome message in the email."

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#262]
In the "I'D LIKE TO CUSTOMIZE MY WELCOME EMAIL.." section of the subscribing settings:

If the message has been changed/customized:
1. Uncheck the checkbox (attempting to go back to using the default message)
2. Click "Update Settings"
Expected: Checkbox stays unchecked
Actual: Checkbox reverts to checked

Secondarily, going the other direction, if the message is unchanged:
1. Check the checkbox
2. Click "Update Settings"
Expected: Checkbox stays checked
Actual: Checkbox reverts to unchecked
This expectation is a matter of opinion and I see how it could be a fine "never mind" feature to revert the checking in this case.

Workaround: Checkbox logic seems to be doing an exact string comparison against "Welcome to {{ newsletter_name }}!  This is the most recent email {{ author_name }} has sent out." (which I went and grabbed from the default of another newsletter) and forcing the checkbox state according to that equality. Thus, entering that magic string will un-check the checkbox.

I think the logic should clearly not flow this way when un-checking the checkbox. Save or discard the custom message (probably discard?), either way, but respect the unchecking.

**Comment by jmduke** [comment]
Fix going live now.
