### ISSUE TITLE
Spammy filter is not loading for some accounts

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#27]

**Comment by jmduke** [comment]
![image](https://user-images.githubusercontent.com/461046/130695433-54ffd7d3-8107-418d-9bd4-3b5c1da58218.png)

`N+1` queries sitatuation.

**Comment by jmduke** [comment]
![image](https://user-images.githubusercontent.com/461046/130695623-602228be-42dd-4719-a2d0-8b8530f11df6.png)

Much better!

**Comment by jmduke** [comment]
@cassidoo The fix should be going live in the next few minutes.

**Comment by cassidoo** [comment]
Thank you!!
