### ISSUE TITLE
"You've created a new newsletter!" email missing one name substitution

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#290]
Low pri, tiny fix

Created new newsletter
Received "You've created a new newsletter!" email
In the body: "you've created a new newsletter entitled on your account named intentionalsociety."

Actual: "entitled on"
Expected: "entitled <name goes here> on"

The newsletter does have a non-empty name.

**Comment by jmduke** [comment]
🙏 Fixed; thanks for the flag!
