### ISSUE TITLE
500 on subscription upgrade

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#313]
Hi Justin

FYI I hit a 500 when trying to upgrade my subscription from a premium article.

We have enabled paid subscriptions and disabled monthly ones (so only yearly).

I have registered with an email address previously, but did not put in my credit card to unlock.

When I try to unlock from the bottom of this article, I get a 500:

<img width="797" alt="Screenshot 2021-12-02 at 10 28 53" src="https://user-images.githubusercontent.com/1426859/144404918-e57b6185-9c29-4d3a-9d0a-f12f89c753ab.png">

https://news.france-insider.com/archive/discharge-from-hospital-in-france-2021-11-16/

that links to:

https://news.france-insider.com/subscribers/296a79e2-1350-4df5-8c60-ba1def834de7/upgrade/monthly

where it 500s. I'll email you directly my email address that I was using.

Thanks

**Comment by jmduke** [comment]
Fix going live right now!

**Comment by ifpingram** [comment]
Hi Justin

Just to confirm, it now doesn't seem to offer the option to click through to a separate page and subscribe. The payment fields for Stripe now appear in the subscription box. 

Is that the correct behaviour? Because if so, the fix is working.

Thanks

**Comment by jmduke** [comment]
Yup, slightly different flows!
