### ISSUE TITLE
More granular tracking

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#315]
I don't know the state of the industry re open-tracking, I hear that iOS is breaking open-tracking for Apple Mail users soon.
However, to the extent that open-tracking works and is a thing, I would like to
**ENABLE open-tracking**
while at the same time
**DISABLE link-rewriting**

I don't like link obfuscation and think click info is not worth the user experience cost, but I would like to use open-tracking as the basic open-engagement info is useful to me with no UX hit.

These things are currently bundled in the "Would you like to opt out of analytics?" setting.

**Comment by jmduke** [comment]
+1. I thought I had this as an extant backlog item already, but apparently not! (Rewriting title)

**Comment by jmduke** [comment]
A couple axes here:

- Click / open / both
- Transactional / newsletters / both

**Comment by jmduke** [comment]
This is live!
