### ISSUE TITLE
Unable to load previous pages of Premium Subscribers

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#321]
When trying to load the previous page of Premium Subscribers, the loading spinner just sticks spinning:

<img width="873" alt="Screenshot 2021-12-06 at 22 36 52" src="https://user-images.githubusercontent.com/1426859/144934047-7fe7091f-7466-4bc5-a303-c8dae70ab41c.png">

**Comment by jmduke** [comment]
Fix going live right now!

**Comment by ifpingram** [comment]
I can confirm, it is now working. Thanks!
