### ISSUE TITLE
Include Unpaid Subscribers in Export?

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#322]
We only accept Premium subscribers, but due to the flow, the first step is to register the email address and then if the person decides not to input their credit card, then it puts their account in an Unpaid Subscriber state. 

We would like to email these Unpaid Subscribers to try to convert them to paying Subscribers. Is it possible to include them somewhere in the data export zip please, as currently we only receive Premium subscribers?

Thanks

**Comment by jmduke** [comment]
Yup, this makes sense (there's a similar behavior for unactivated subscribers too who haven't gone through double opt-in). This change is going live this evening.

**Comment by ifpingram** [comment]
Perfect, that works well. Many thanks.
