### ISSUE TITLE
Gift subscriptions are unable to access Web Premium content

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#344]
Hi Justin

Is it possible to allow Gifted subscriptions to access the Web versions of the Premium articles please?

Currently, when we use an email address that has a gift subscription, to try to unlock the Premium articles on the Web Archive, the system returns the message:

"That email address is already subscribed, but you can unlock all newsletters if you'd like." 

Thanks!

Ingram

**Comment by jmduke** [comment]
Fix going live right now!

**Comment by ifpingram** [comment]
Works perfectly. Many thanks for quick resolution!
