### ISSUE TITLE
Inconsistent wrapping in plain-text emails

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#351]

**Comment by brainwane** [comment]
![partially-wrapped-text](https://user-images.githubusercontent.com/842790/146586760-2239ecb9-b0cd-4958-98e0-ab59de075988.png)

Screencap of how [this email](https://buttondown.email/Changeset/archive/5-book-recs-internship-program-tips-and-a-holiday/) looked in Thunderbird on Linux.

**Comment by brainwane** [comment]
![Fastmail-partially-wrapped-text](https://user-images.githubusercontent.com/842790/146587214-c8751094-5deb-4138-80d2-a269dfff89b7.png)

Screencap of how that email looked in the Fastmail web view in Firefox on Linux.
