### ISSUE TITLE
Allow updating subscriber address in Notes modal

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#356]
(I tried several searches first because I thought this would be a dupe, but didn't find it)

A subscriber sends me a message, "Hey, I'm changing my email address from X to Y"

Desired: When I pull up the notes or edit (meta)data modal, I can change the email address associated with that ID
Actual: Have to unsub/delete the old address, and sub/add the new address, which is not associated with the old one in any way.

Event history is lost. Subscriptions... how does this work for paid subscribers?

**Comment by james-baker** [comment]
And because of #256, I don't possess an "unsubscribe" option on my side equivalent to what the subscriber DOES have.

**Comment by jmduke** [comment]
+1. (Ironically, this works _for_ paid subs but not free ones, since you can change email addresses in the Stripe dashboard...)

**Comment by jmduke** [comment]
Going live this evening :)
