### ISSUE TITLE
Rich-text-to-markdown conversion incorrectly marks embedded URLs as self-referential links

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#405]
If I send while in Rich Text mode, I get tweet embedding and straight quotes.
If I send while in Markdown mode, I get smart quotes and no tweet embedding.

![image](https://user-images.githubusercontent.com/89615/148442759-52cacb0a-2177-49ec-a287-2caa20a638d4.png)

Desired: Wish I could have both things in the same newsletter.

Potential tactical fix: Have tweet embeds insert their equivalent markdown/html when switching from Rich Text to Markdown edit mode

Ideal general design fix in my head: Make markdown rendering always-on and canonical. The editing mode should just be a way of looking at the content, and shouldn't result in any rendering differences ever. Round-tripping through edit modes should never affect the content.

**Comment by james-baker** [comment]
Workaround copy the HTML structure from the Preview rendering of Rich Text mode, and insert that in Markdown mode? Should this work, or is it missing any embedded-tweet magic in the "for real" rendering path?

This is what it looks like:
`<div class="tweet">
<blockquote>
<div class="header">
<div class="author">
                <a class="link link_blend" href="https://twitter.com/jambarree">
          <span class="avatar">
            <img class="avatar-image" src="https://pbs.twimg.com/profile_images/1125880503603585024/qe4Bwt1o_normal.png">
          </span>
                    <span class="identifier">
                    <span class="name" title="James">James</span><br>
<span class="screen_name" title="@jambarree">@jambarree</span>
                    </span>
                </a>
            </div>
</div>
<div class="body">
<p class="text">If you detach from the concept of a single coherent self, then you no longer need to shame yourself for being a hypocrite.  Be compassionate towards all your shards of self.</p>
<br>
<div class="metadata">
                <a class="link_blend" href="https://twitter.com/jambarree/status/1130337713461137408">May 20, 2019, 5:01 a.m.</a>
            </div>
</div>
</blockquote>
</div>`

**Comment by jmduke** [comment]
Nice, thanks for the detail here. I think you hit on the key which is:

> The editing mode should just be a way of looking at the content, and shouldn't result in any rendering differences ever. Round-tripping through edit modes should never affect the content

Clearly this isn't the case here, but is certainly the _desired_ behavior. I'm actually surprised and cannot reproduce the case you're describing trivially: mind sharing the full text? I suspect something in the markdown rendering is choking on some other part of your email, and you're getting some fallback logic. To wit, below:

![image](https://user-images.githubusercontent.com/461046/148483131-29d79c5c-a39e-435d-9627-8ab315e49748.png)

**Comment by james-baker** [comment]
Okay I managed to repro:

1. Start in Rich text mode.
2. Paste URL. (it gets auto-linkified in the rich text, and embedded in the preview)
3. Switch to Markdown mode.
4. Link gets turned into standard markdown link, renders as raw link in preview

Looks like maybe rich text mode should not both auto-linkify AND auto-embed --- maybe it's the linkify that induces the render change.

usability FYI: I did not know and had not discovered that deleting the whole link and re-pasting the URL in Markdown mode would trigger the embedding. It did not occur to me that embedding magic would be a feature of markdown mode.

**Comment by james-baker** [comment]
Further comment on the key point above:
I have (semi-painfully) learned "never hit publish while in rich text mode" because then my quotes are dumb and my triple-dashes aren't em-dashes. Having authors learn to modify their behavior this way seems like a design antipattern.

Is your approach to this going to be "Fix all differences between the two renderers" or "only use one renderer"? Rich text edit mode does not appear to be WYSIWYG, so do you actually have three renderers including the preview renderer?

**Comment by jmduke** [comment]
Beautiful, t/y for the repro steps here. It's the 'turning to a raw link' that's the issue here, and thankfully that's not too hard to overcome. Renaming this issue to be more specific

**Comment by jmduke** [comment]
And agreed with your comment. I don't mean this as a non-answer, but as elucidation:

- There is only one renderer ("renderer" meaning "what you type" -> "final HTML") for both the Rich Text and the Markdown flows.
- However, the Rich Text has an additional compilation step since "Rich Text" is in a weird format (think block-based JSON).

The pain comes from two things, I think:

1. The "final HTML" returned by the rich text flow is asymmetric with the Markdown
2. The rich-text-to-Markdown flow (and vice-versa) isn't reflexive.
