### ISSUE TITLE
Add option to reinstate premium sub in event of accidental unsubscription

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#411]
I think we can do a couple things here:

- [x] Create an inert type `churning`
- [x] Unsubscriptions should trigger a cancellation in the future, rather than a straight-up deletion
- [x] Mark folks who have unsubscribed as `churning` rather than outright bumping them
- [x] Add an action to re-enable `churning `subscribers
- [x] Listen to the specific deletion event

**Comment by jmduke** [comment]
Ah, thanks for the ping; I think I should be able to get this done either today or early this week.

**Comment by Mimort1** [comment]
Any news on this one Justin? I appreciate I have kept you busy with other issues.

**Comment by jmduke** [comment]
Ha, no — but this slipped my mind. I'm bringing it into the February sprint to keep track of it.

**Comment by jmduke** [comment]
This is going live this afternoon; there's a new filter, "churning" subscribers, and for those subscribers specifically you can re-instate their subscriptions!

**Comment by Mimort1** [comment]
Justin, I see the 'churned' list, but there does not appear to be a means of reinstating the subscription. Nothing offered in drop-down menu on right click with the mouse.

**Comment by jmduke** [comment]
Ah, try `Churning` rather than `Churned`. (That's confusing language; I'll clean it up.)
