### ISSUE TITLE
the visual UI state of the draft recipient checkboxes is incorrect - they appear all-checked initially

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#430]
Describing the front-end experience to match your logs.
Date: Sat, 15 Jan 2022 00:12:29 GMT (and nearby)

Request payload:
body: "<snipping out this text>"
email_type: "public"
excluded_tags: []
included_tags: []
recipient: ""
recipients_type: "subscribers"
subject: "IS session 1/16 - Deeper Parts (IFS)"
subscribers: "d3d39448-6319-4885-a7df-b538326f366b"

Response is generic-looking HTML for "500 Internal Server Exception"

**I've chosen a draft recipient, and this appear to be the broken part.**
When I go back to "Send to yourself" mode, it sends - but FYI then the template variable metadata doesn't work because there is no metadata on "yourself".

While I'm here, separate bug (sorry for mixing): the visual UI state of the draft recipient checkboxes is incorrect - they appear all-checked initially, though in the underlying model I think they're all unchecked. (I click the target recipient off, then on, then they are the only one truly selected despite all the other boxes still looking checked.)

**Comment by jmduke** [comment]
No worries! On the first front: pushing out a fix now (I think I see the issue; it's trying to find a slug that doesn't exist.) Mind trying again in ~10 minutes?

**Comment by james-baker** [comment]
Fix verified: sending draft to specific recipient works for me now.

**Comment by jmduke** [comment]
:+1: Rephrasing this to look into the second bug.

**Comment by jmduke** [comment]
Fix going live.
