### ISSUE TITLE
template variables not supported in titles

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#441]
Using a template variable insertion like {{ subscriber.metadata.firstname }} works in the body text, but not in the title of an email?

Desired: Support for template processing in titles too

I don't know if this is a bug or feature request. Thus, supported scope could then be documented (represented by #219 )

**Comment by jmduke** [comment]
I'd call this is a feature request (though you thinking that this would 'just work' is v reasonable), and a fairly easy one.

**Comment by jmduke** [comment]
This is going live in the next few minutes.
