### ISSUE TITLE
Unable to delete emails from subscribers overview

### ISSUE THREAD

**Issue by stefanjudis** [buttondown-email/roadmap#448]
I selected an email address via the search and opened it.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/962099/150484638-de8921c9-7682-47fe-a6d2-65d4976a4aa2.png">

Clicking `Delete` leads to the following modal.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/962099/150484470-5d1b2e67-b837-46ab-9e61-e1fb3be0c3ec.png">

It shows that `0` email addresses were selected and the deletion doesn't work.

**Comment by jmduke** [comment]
Thanks for the repro steps. Fix going live right now.
