### ISSUE TITLE
Improve performance of `/analytics` for year+ timespans

### ISSUE THREAD

**Issue by stefanjudis** [buttondown-email/roadmap#449]
I started seeing more and more `503` errors in my analytics sections.

From the archive and looking at specific campaign analytics it feels like a 50/50 chance that the request is not timing out.

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/962099/150485139-5aff2149-049e-402f-86cd-f935c5dc1436.png">

The overall analytics route seems to have the same issue and it's been entirely broken for me for some time now. 

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/962099/150485282-9077d79b-e557-4076-a382-91b1a679e78f.png">

Thanks. :)

**Comment by jmduke** [comment]
I have a backfill for the latter issue rolling out right now, but the former is surprising. Taking a look.

**Comment by jmduke** [comment]
Okay, figured out the issue here; the payloads being returned are suboptimal. A couple steps:

- [ ] Remove prefetch on `email_event__subscriber`
- [ ] Don't calculate the unique `open_count_pairs` and `url_count_pairs` ahead of time; shift those to be async with separate (and ideally paginated) calls

**Comment by jmduke** [comment]
Both things should be going live in the next ~15 minutes.

**Comment by jmduke** [comment]
@stefanjudis mind giving this a try later this evening, and re-opening if you're still seeing timeouts on the first bit?

**Comment by stefanjudis** [comment]
Analytics for a sent email seems to work. 🎉 `/analytics` is still 503'ing for me. :)

**Comment by jmduke** [comment]
Progress! It looks like this is for longer-term timeseries; updating the issue.

**Comment by jmduke** [comment]
One big issue: an `O(n)` in the calculation of each eligible subscriber for each email.

**Comment by jmduke** [comment]
This actually feels like a pretty good idea to denorm; "who did we try to send this email to originally?" is a pretty reasonable snapshot.

**Comment by jmduke** [comment]
Closing in favor of https://github.com/buttondown-email/roadmap/issues/732.
