### ISSUE TITLE
Temporarily reordered archives is incorrect in author interface

### ISSUE THREAD

**Issue by Mimort1** [buttondown-email/roadmap#464]
The archive list of articles does not remain in chronological order if a subsequent change is made to the article or it is opened for copy and paste purposes.

**Comment by jmduke** [comment]
Easy repro step: open an archived email, change the subject, hit save.

**Comment by jmduke** [comment]
Fix going live now.

**Comment by Mimort1** [comment]
Justin, Not sure this one has been finally cracked. I still do not have them in date order if I click on one after publication.

**Comment by jmduke** [comment]
@Mimort1 mind providing repro steps (or sending me a video over email)?

**Comment by Mimort1** [comment]
Justin,

 

Here is a screenshot, from which you can see some articles out of order. It seems to occur when I go in after publication to change something or use some coding from the article.

 

David
