### ISSUE TITLE
DMARC (DKIM / SPF)

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#476]
Hi Justin

We have set up a custom sending domain, and you have provided the DKIM records for it, which we have set up also - thank you. I'm now wondering what we might need to do to get DMARC working with this sending domain?

Would we also need some SPF records set up, if so, would you know what to add please?

Thanks!

**Comment by jmduke** [comment]
DMARC only requires one of DKIM & SPF, and SES (which your newsletter is using on the backend) just exposes DKIM!

**Comment by ifpingram** [comment]
Ok, thanks - I didn't realise SES only used DKIM. Do you happen to know what we need to do to get DMARC working with the DKIM - this is outside of my area of expertise.

Thanks

**Comment by jmduke** [comment]
Are you seeing DMARC not enabled? It should be working as-is!

**Comment by jmduke** [comment]
Closing this out.
