### ISSUE TITLE
changing visibility surprise-emailed all my subscribers

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#481]
I won't let it bite me again, but this is an "OMG did that really just happen" level embarrassment bug for me.

Situation: I'm trying to make a "welcome message email" to send to new subscribers.
I didn't want to send it to existing subscribers, so I selected "Send to nobody" while authoring it.
After that, I looked at the /archive page and noticed that its status was "Archived" versus all the others being "Public". Hmm, it's not public, does that mean that I somehow hid it so people can't see it? What does "Archived" even mean? Let me check the edit dialog...

(Original state: none of those three buttons are selected)
![image](https://user-images.githubusercontent.com/89615/151848227-85212f20-7ced-435f-b120-4372399bfcaa.png)

Hmm, "Archived" isn't even an option here. That's confusing. Well, it's not premium or private, I guess. This should be safe to click "Public" and then I'll know it's similarly accessible/available to add to my subscription welcome-message settings, right?
(I click Public, then Save)

Expected: Ho hum, I change the state of a model object, nothing else should happen
Actual: IT EMAILED EVERY SUBSCRIBER

There was no clue or indication that it was going to, or did, email everyone. I saw a copy show up in my inbox a minute later, and then checking the analytics told me that yes, it had emailed everyone a message that wasn't intended for them.

**Comment by jmduke** [comment]
_what_! that is... an awful bug, and also one that I'm not able to reproduce. Roughly how long was the distance from you creating this email and you changing the visibility?

**Comment by james-baker** [comment]
Not long...
Let's see, newsletter publish datetime says 1/31/2022 05:57:18.442

Headers on the email:
Date: Mon, 31 Jan 2022 17:59:47 +0000
Message-ID: <0100017eb14af7ba-b536fcae-1336-462e-9d6c-d785131d3638-000000@email.amazonses.com>
List-Id: <is-participants.buttondown.email>
X-Metadata: {"email": "171b80f3-dc6f-4a1a-a8f6-08331ad6dab5"}
Feedback-ID: 1.us-east-1.2x8rECq2CV6m6fb8lsKtSHlWoHQo1yJKAZhCZwvfe7s=:AmazonSES
X-SES-Outgoing: 2022.01.31-54.240.46.1

So, looks like more than one minute, but less than three.
(How long is the built-in delay on sending emails? Does "visibility" connect to the "send to" selection?)

**Comment by jmduke** [comment]
Okay, yup, that's terrible. Buttondown has a ~3-5 minute delay to let people delete/undo, and of course it checks the latest state of the model afterwards.

An easy fix here, but deep apologies here — I track changes to the visibility state, so pushing a fix to make it only check the _original_ state when sending.
