### ISSUE TITLE
Webhook body customization

### ISSUE THREAD

**Issue by reesericci** [buttondown-email/roadmap#527]
It would make webhooks infinitely more useful if I could customize the JSON request body for the webhook. As every service expects a different body, I would like to be able to define the request with template syntax based on the event that was selected.
I don't want to have to spin up a server to "translate" the Buttondown webhooks to slack, discord, etc.

--reese

**Comment by jmduke** [comment]
Ahh, as in transforming the request from Buttondown's format into e.g. Slack's? Have you investigated using something like Zapier for that purpose?

**Comment by reesericci** [comment]
Yes, I know Zapier can do it, but it would be nice to not need a 3rd party tool.

 P.S - why is it blocked?

**Comment by jmduke** [comment]
"Blocked" just means I'm waiting on a response!
