### ISSUE TITLE
attempted gmail subscriber didn't receive self-triggered confirmation emails

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#529]
Newsletter: intentionalsociety
Subscriber ID: 253

Events dialog shows;
02/14/2022 @ 12:48pm
Received subscription confirmation email

but they report never receiving anything.
They also tried (via the same front-door path, entering their email on intentionalsociety.org) yesterday, 2/23, and again did not receive  any confirmation email. This also didn't show up in the "Events" list at all.

Today, the 24th, I just used the "Send reminder" feature - and then they immediately received that email and were able to complete their subscription.

I'm sure "I didn't get the email" is a common false-positive report, and a truly hard problem to increase the 9's of reliability on, but I trust this person enough, and the contrast between the 1st and 2nd code paths' behavior is striking enough, that I thought this worth reporting.

**Comment by jmduke** [comment]
Am I understanding that they used the same email for both the 2/14 and the 2/23 attempt? Or separate emails?

**Comment by james-baker** [comment]
Yes, same email. (Which is of course also the same email that the "send
reminder" went to)

**Comment by james-baker** [comment]
Oh my — I didn't expect an easy repro, so, yay? (with the ? because I hope this hasn't been happening widely)

**Comment by jmduke** [comment]
I wouldn't say _easy_, but I think there's a better messaging I can do here. Will post more in depth before closing out.

**Comment by james-baker** [comment]
Can you comment on the scope/severity of the problem?
I just got a spurt of 15 new subscribers in the last few days, and I was pleased-yet-surprised to see that no one was stuck in "unconfirmed", which... I think that's a new record for the number of consecutive sign-up successes I've seen across the first 250.
