### ISSUE TITLE
Document page sizes in the API

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#545]
Whilst I see that the API schema docs say pagination exists, currently both the next and previous keys in our data array returned from the API email list are null:

```php
array:4 [[▼]()
  "count" => 39
  "next" => null
  "previous" => null
  "results" => array:39 [[▶]()]
]
```

Can you tell me at what count pagination kicks in, if it is implemented? 

If it is not yet implemented, then no worries; I will implement it myself server side.

Thanks!

**Comment by jmduke** [comment]
It is implemented, but only kicks in at 100! Changing this issue to document that in the schema (e.g. [here](https://docs.buttondown.email/api-reference/emails).)

**Comment by ifpingram** [comment]
Brilliant, thanks for the clarification.
