### ISSUE TITLE
Bug: When archives are disabled in settings, subscription form still links to the archives after confirming your email

### ISSUE THREAD

**Issue by retlehs** [buttondown-email/roadmap#560]
noticed this minor issue when testing a subscription form when archives are disabled:

1. enter email address into form<br> <img width="789" alt="image" src="https://user-images.githubusercontent.com/115911/157993824-37d8c989-64fe-4f1c-9489-270120e0cc82.png">
2. click the confirmation link received via email
3. go back to the form and click the "I've confirmed my email button"
4. archive link appears<br> <img width="784" alt="image" src="https://user-images.githubusercontent.com/115911/157993874-22faa2ee-dde8-40aa-a995-c74990c2a905.png"> <br> 👇 <br><br> <img width="439" alt="image" src="https://user-images.githubusercontent.com/115911/157994053-90c713b2-a5d6-4d3e-9591-bde8a339deeb.png">

**Comment by jmduke** [comment]
Doi, t/y — will get a fix out for this tonight/early tomorrow.
