### ISSUE TITLE
Expose email events via the API

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#565]

**Comment by jmduke** [comment]
@stefanjudis — OOC, what sort of specific events/shapes were you looking for? I’m definitely interested in exposing this information, but I haven’t seen any _great_ prior art for how to expose high-dimensionality data at scale that I love.

**Comment by stefanjudis** [comment]
Not sure if this is the correct issue. I'm mainly interested in this information for each previously sent email.

<img width="785" alt="image" src="https://user-images.githubusercontent.com/962099/198880155-e858f207-6557-443c-90d2-a4ecb10b68cb.png">

So, ideally I'd like to build a summary for sponsors telling them delivered emails, open rate and click through rate. :)

**Comment by jmduke** [comment]
Totally makes sense. Confining it to the email object specifically is fairly painless.

**Comment by stefanjudis** [comment]
Yay! 🎉

**Comment by stefanjudis** [comment]
@jmduke Hey Justin, no rush and really no pressure here, but I'm having two weeks off soon and want to tackle my sponsorships pages. 

Do you think this addition will come soon'ish? If yes, cool! If not, also cool (just wouldn't want to implement something else to throw it away shortly after).

Thanks!

**Comment by jmduke** [comment]
Yes! I should be able to get this set for you by the end of the week; marking it as SFD.

**Comment by stefanjudis** [comment]
You rock! 👏 💯
