### ISSUE TITLE
Unsubscription Success email link can't be configured

### ISSUE THREAD

**Issue by retlehs** [buttondown-email/roadmap#572]
the email link on the unsubscription success view links to justin. can't figure out a way to configure or change this - sorry if i missed something!

@ https://buttondown.email/unsubscription-success/xxxxxxx/:

> If you think there's been a mistake — or if you've changed your mind and would like to resubscribe — please email [me](mailto:justin@buttondown.email) and I'll get it sorted out.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/115911/158653183-c1b38cda-2a1d-4b6b-aee1-6ca0f2bc7dec.png">

**Comment by jmduke** [comment]
Fix rolling live rn!

**Comment by retlehs** [comment]
✅ confirmed over here, thank you!
