### ISSUE TITLE
Better `Edit Email` flow

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#61]
- [ ] Full-featured editor, not just the tiny little textbox
- [ ] Ability to upload a custom thumbnail for preview
- [ ] Ability to set OpenGraph (et al) metadata

**Comment by jthingelstad** [comment]
💯

**Comment by jmduke** [comment]
Hahah yup, this is one of the things that I had in mind.

**Comment by jmduke** [comment]
Closing in favor of https://github.com/buttondown-email/roadmap/issues/784, where all of the above (and more!) are happening.
