### ISSUE TITLE
utm_source not setting in cookies from iFrame

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#616]
We are passing the utm_source into the iFrame, on the page:

https://france-insider.com/?utm_source=foobar

This is correctly tagging the subscribers with the utm_source when they register, which is good. However, if the user decides not to subscribe there and then, but later on goes back and directly opens up:

https://news.france-insider.com

There is no utm_source cookie with the value of foobar. Therefore if they subscribe from the form above, their utm_source is not recorded.

Thanks!

**Comment by ifpingram** [comment]
Do you have an ETA for this at all please Justin? We'd like to start promoting the links to partners as soon as we can.

Thanks!

**Comment by jmduke** [comment]
Hey, yes — I should be able to get this taken care of this coming week.
