### ISSUE TITLE
Reprice Buttondown

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#62]

**Comment by nibl** [comment]
I think tags should be included from 1-1000 because it's really impractical to add tags manually. Imagine doing that after reaching 1000 subscribers 😯. It's just not something anyone wants to do retroactively.

**Comment by nibl** [comment]
If it's the 100-1000 that needs monetizing, how about charging $1 per 100 subscribers as of a certain amount? e.g. $2 when reaching 200 subscribers, $3 for 300...That works in relation to $9 for 1000.

Nobody else offers staggered pricing at lower subscriber numbers. The approach would encourage authors to consider monetization earlier. Monthly amounts of even $1-$2 can work for creators, as proven by Patreon.

**Comment by ifpingram** [comment]
You undersell this Justin.

**Comment by reesericci** [comment]
Possibility for zapier in the $9/mo tier? I would also like custom domains but that might be a stretch.

**Comment by jmduke** [comment]
The above is a little outdated, but the good answer is yes! Most of the 'premium' functionality is moving to a lower price point.

**Comment by reesericci** [comment]
also, i just tried zapier on my free plan and it seems to work :)

**Comment by kuenwei** [comment]
Hi @jmduke , is there any update about the repricing?

**Comment by jmduke** [comment]
@kuenwei It's now live for new folks, and I'm in the process of rolling out the comms to existing folks to migrate them over. If you're interested, please email me!

**Comment by nibl** [comment]
@jmduke What happens from 101-999 subscribers?

Btw, prices do not show on mobile. Is that intentional?

**Comment by kuenwei** [comment]
> @kuenwei It's now live for new folks, and I'm in the process of rolling out the comms to existing folks to migrate them over. If you're interested, please email me!

ah~ understood, just would like to pay and not sure what will happen if pay for $29 now as I am an existing user?

**Comment by kuenwei** [comment]
> @jmduke What happens from 101-999 subscribers?
> 
> Btw, prices do not show on phones. Is that intentional?

[https://buttondown.email/pricing](https://buttondown.email/pricing) just saw the new pricing table. guess, for 101-999 have to pay for $9/mo, and will get more capabilities, such as custom domain, etc.

**Comment by reesericci** [comment]
Wait, @jmduke - you don't get customer service for free? Or is that like a dedicated chat or something.

**Comment by jmduke** [comment]
@kuenwei Whoops, that's my bad — pushed a fix this morning to the CSS.

**Comment by kuenwei** [comment]
@jmduke so I can still pay from billing page for 29/mo now?

**Comment by reesericci** [comment]
That makes sense, thanks for the clarification! @jmduke
