### ISSUE TITLE
Add class to rendered Markdown images

### ISSUE THREAD

**Issue by stefanjudis** [buttondown-email/roadmap#657]
I'd love to style embedded markdown images with a border, but the last time I checked I couldn't just add `img {}` to the stylesheet because it's matching the emojis, too. 

It'd be 💯 if the markdown renderer could add a `markdown-image` class or something. :) 

Thanks a bunch!

**Comment by stefanjudis** [comment]
I just tried it and I don't think it's working. :/ 

<img width="494" alt="image" src="https://user-images.githubusercontent.com/962099/164031415-abd59b99-8758-4657-88ea-aff065e4188b.png">

Inspecting it in gmail shows two classes and none of them is matching the custom CSS I defined.

<img width="962" alt="image" src="https://user-images.githubusercontent.com/962099/164031585-99325be7-a060-4a4d-b4d9-818e0b03fa09.png">

**Comment by stefanjudis** [comment]
@jmduke Is this really resolved? It's still not working for me. :/

**Comment by jmduke** [comment]
Oh lord — sorry about this, it is resolved but my CI has been down for the past week or so due to the Heroku/GitHub [issues](https://status.heroku.com/incidents/2413) and I forgot to deploy the merge commit. Pushing this live right now; thank you for the prod.
