### ISSUE TITLE
bug: "Ask for help" menu link is broken

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#696]
In the main hamburger UI menu dropdown, the "Ask for help" link is currently:

https://buttondown.email/mailto:justin@buttondown.email

which looks like a code loop is prepending the base url to all links, but it shouldn't do that to mailto links. Hopefully it's an easy refactor.
Expected: mailto:justin@buttondown.email
Actual: 404 page

**Comment by jmduke** [comment]
Fix going live! (This is what I get for being clever with external link changes.)
