### ISSUE TITLE
docs reference non-existent setting

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#697]
https://docs.buttondown.email/getting-started/sending-from-a-custom-domain

contains this image:
![image](https://user-images.githubusercontent.com/89615/166092436-bbf003cc-8d47-498e-bb71-6e0a298ad49c.png)
"Would you like to send emails from Buttondown's domain?"

which... seems obsolete AFAICT? Maybe it just does this always/automatically now if you're not using a custom domain?
Expected: maybe this part of the doc just gets deleted? be not confusing, whatever the outcome
Actual: looked on all the settings pages and couldn't find it

**Comment by james-baker** [comment]
While we're on this page: This page should probably have some sort of link to or indication that https://docs.buttondown.email/sending-domains/sending-from-dreamhost exists - the page that actually contains the DNS instructions that I was looking for.

(UX story: I opened the help, tried to search for "custom domain", realized after a few tries that I couldn't type any spaces, searched for "domain", and picked the page that *didn't* have the " - Dreamhost" suffix on it, since I don't use them.

**Comment by jmduke** [comment]
Agreed on both keys.
