### ISSUE TITLE
Add tooltips to rich text editor icons

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#702]

**Comment by coreycaitlin** [comment]
<img width="424" alt="Screen Shot 2022-04-30 at 8 28 08 PM" src="https://user-images.githubusercontent.com/1450354/166130933-0889f5b0-30c1-4ad4-bac6-8c159ee66167.png">

Suggested microcopy for the tooltips:

- Bold
- Italic
- Insert link
- Heading 1 or Large heading
- Heading 2 or Medium heading
- Heading 3 or Small heading
- Block quote
- Bulleted list
- Numbered list
- Code block
- Insert image
