### ISSUE TITLE
adding an already-subscribed addresses now deletes the existing subscriber (instead of no-op)

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#704]
When adding subscribers from https://buttondown.email/subscribers, I recall previous behavior that would clearly indicate "this person already exists in your list" feedback and not do anything.

Now, it *always* says "Added {address}!", and seems to delete the old subscriber item (and all their event history!) from the subscriber list, creating a new subscriber with a new ID in unverified state even if that user was previously verified. (Testing it on myself, it didn't seem to send out a new welcome email or new subscription-confirmation request.)

But this seems to leave things in a bad state: did I accidentally UNsubscribe people by accidentally replacing their subscriber data?

I would very much prefer the behavior go back to "it's safe to enter addresses regardless of whether they're already there"

**Comment by jmduke** [comment]
This sounds like a bug: the intended behavior is as you described. Will take a look!

**Comment by james-baker** [comment]
For example, my subscriber # 1 on intentionalsociety is now gone from the UI, replaced by subscriber # 331. (both me) AND I currently believe that subscriber did NOT receive my latest newsletter! (Since the new subscriber entity is in an unconfirmed state)

**Comment by james-baker** [comment]
I can verify this bug's continued existence as of 5 days ago - I did re-add the subscriber that I incorrectly unsubscribed, and they got a new ID, new history, and their old ID/data disappeared (such that there's nothing there even in the "All subscribers" list).

**Comment by jmduke** [comment]
Got a repro for this; I need to jury-rig a little notice together explaining that the previous subscriber will be re-instated as well.

**Comment by jmduke** [comment]
![image](https://user-images.githubusercontent.com/461046/204631284-3b24a7c2-2811-4b27-9bf3-03ade70b057b.png)

Going live this afternoon! Thanks for the patience, @james-baker.
