### ISSUE TITLE
Figure out how to sync `REDIS_URL` between apps

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#716]

**Comment by dstarner** [comment]
I believe Buttondown is hosted on Heroku, no? You can [attach Redis to another app](https://devcenter.heroku.com/articles/managing-add-ons#using-the-command-line-interface-attaching-an-add-on-to-another-app) pretty easily and it will "keep in sync for you. You can specify the attachment name I believe with the `--as=REDIS_URL` option.

**Comment by jmduke** [comment]
oh absolutely brilliant, t/y
