### ISSUE TITLE
Add email.sent event webhook

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#775]
Please can you add an event for when the emails are sent to the user base. We require a webhook to hit our server, so that we can pull in the latest list of articles via API every time a new article is sent.

Thanks!

**Comment by jmduke** [comment]
Done :)

**Comment by ifpingram** [comment]
We have just sent an email about an hour and a half and the webhook didn't fire as far as I can tell, and neither can I see an event in the last 100 events, the list of which goes back earlier than when the email was sent. 

Can you investigate whether the event did fire please, and if the webhook did too? I can't see it is a problem with the webhook our side, as it works fine when I hit it manually.

Thanks!
