### ISSUE TITLE
Urgent: Premium / Gifted article login leads to 404

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#777]
If we log in, either with a Premium or a Gifted subscriber, the article behind the login 404's.

Example URL from which we try login.

https://news.france-insider.com/archive/surviving-spouse-right-to-marital-home

The behaviour is slightly different for both users:

- Premium subscriber - upon login, the article is not displayed automatically, but instead they are displayed:

<img width="776" alt="Screenshot 2022-07-05 at 12 45 12" src="https://user-images.githubusercontent.com/1426859/177320268-832dc3f8-0329-4c4d-a76b-bb18baa9e9f5.png">

Upon clicking the Read Full Article button, the following URL is opened in a new tab/window:

https://news.france-insider.com/subscribers/1c77ed2c-4c5a-408d-80f7-1686f0bf9653/archive/archive 

I.e. with the users GUID then /archive/archive 

Ideally it would be best for the actual article to just become visible, rather than necessitating another click of a button to access the article.

- Gifted subscriber - as the user does not need to manage their subscription, there is not button displayed, but instead the same format URL as above is opened directly in a new tab/window. Again 404s.

Thanks!

**Comment by jmduke** [comment]
Got it; fix for this is rolling live right now. Holding this issue open until I can verify the solution in prod.

**Comment by ifpingram** [comment]
Justin - this seems to be broken again. I have emailed you. Thanks.
