### ISSUE TITLE
Revue's new table layout is breaking imports

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#793]

**Comment by jmduke** [comment]
https://buttondown.email/ricky/archive/sheriff-gangs-endangering-lives-to-hoard-funds/ has an example of the breakage due to unclosed style tags

**Comment by rdela** [comment]
Rock on sir

**Comment by jmduke** [comment]
@rdela you beat me to emailing you — mind if I re-run your import to fix the stuff now?

**Comment by rdela** [comment]
Yes please! Wow I ❤️ Buttondown!!

**Comment by rdela** [comment]
looks like it worked a treat
