### ISSUE TITLE
Churning users unable to login

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#796]
If a churning user is not logged in, when they try to login, they are presented with the following message:

<img width="830" alt="Screenshot 2022-07-15 at 11 20 27" src="https://user-images.githubusercontent.com/1426859/179204482-efa116e2-5c8d-47b0-a814-504ea717202b.png">

Clicking "Manage subscription" opens the Stripe billing page in a new window, but the user is not logged in, and so they cannot view the article. Clicking refresh does not log them in to open the article either. 

A churning user should still have access to the articles until the end of their subscription without the need to manage their subscription.

**Comment by jmduke** [comment]
I think this is the same root cause as the previous issue in this vein; you've got "all archives" turned off, so this gets hidden. Pushed a flag for you in the meantime; should be live in a few minutes.

**Comment by Mimort1** [comment]
This issue appears to be unresolved as I remain unable to obtain access using the mail address of the subscriber concerned.
