### ISSUE TITLE
Gifted users should not be able to manage subscription

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#797]
Gifted users when logged in are presented with the following at the bottom of the page:

<img width="787" alt="Screenshot 2022-07-15 at 14 05 55" src="https://user-images.githubusercontent.com/1426859/179229581-7d77a571-170d-4ec1-ac33-edf0adfb3f0d.png">

The link then takes the user to a page that says:

<img width="575" alt="Screenshot 2022-07-15 at 14 10 10" src="https://user-images.githubusercontent.com/1426859/179229690-40a6ce94-90e3-49aa-9797-36d627c9d870.png">

As the user is gifted, there is no need to display this message in its current form, nor provide the link.

Thanks

**Comment by jmduke** [comment]
Fix rolling live right now.
