### ISSUE TITLE
Add support for multi-user/multi-author newsletters

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#8]
The vast majority of this work is going to be in breaking out the 1:1 relationship between `Newsletter` and `Account`. Critical path solution would be as "simple" as:

1. Create `AccountConnection` object that links an account and a newsletter.
2. Define a list of `ConnectionRoles` (`owner`, `editor`, `admin`, etc.)
3. Figure out an invite/authorization flow.

**Comment by egli** [comment]
Hm, interesting, thanks. I really like the simple interface of buttondown but I want multiple users to be able to author the same newsletter.

**Comment by jmduke** [comment]
Totally makes sense! Want me to ping you once the feature's live?

**Comment by egli** [comment]
Yes, please ping me
