### ISSUE TITLE
When renaming a second newsletter, Buttondown renames the entire account & user as well

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#80]

**Comment by JPFlintoff** [comment]
Thank you very much Justin. 
Glad to have helped to confirm it's a bug (!) and sorry to put you to trouble with it.

**Comment by jmduke** [comment]
Of course! Sorry for the pain — will get it resolved soon.

**Comment by jmduke** [comment]
Fix going live right now!
