### ISSUE TITLE
Analytics for multiple emails on archive page seems to be broken

### ISSUE THREAD

**Issue by stefanjudis** [buttondown-email/roadmap#803]
Heyoooo. 👋

For a while now I can't compare email analytics. I click multiple emails from `/archive` and hit analytics and the open modal never shows any data. Diving into the network panel shows that there's a `bad request`.

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/962099/179845096-99ce9ef3-885a-4281-9069-d9b7a38b3ba2.png">

**Comment by jmduke** [comment]
Oh, gross — it looks like some `%20`s are getting thrown into your URL somehow. If you remove them they should work (and a fix is going live now to fix the internal link.)

**Comment by stefanjudis** [comment]
Dang!!! You're speedy Justin. Thanks for looking into it. :) 🙇‍♂️

**Comment by stefanjudis** [comment]
Fiddling with the URL does the trick though. :) I'm closing here and will reopen in case it's not fixed in a few days! 

Thanks a bunch!
