### ISSUE TITLE
Possibility to define a pre header text

### ISSUE THREAD

**Issue by stefanjudis** [buttondown-email/roadmap#813]
Heyo, I just read [an article on "great subject lines"](https://inboxcollective.com/how-to-write-a-great-subject-line-for-your-newsletter/) and it mentioned the importance of preheader text. Which I'm also familiar with when I worked with Marketing teams.

Does Buttondown support preheader text?

**Comment by jmduke** [comment]
(I promise I do not stalk my roadmap this aggressively, you just have a habit of writing in as I am clearing my inbox.)

Yes! If you hit the "Customize web archive" button you can add a `description`, which gets used as a preheader:

![CleanShot 2022-07-23 at 14 35 54](https://user-images.githubusercontent.com/461046/180618545-b288b0d4-eb55-407e-ab4c-71a6dc4d4113.png)

(The fact that this is modal references "web archives" and this is functionality for the actual email is problematic; it's getting renamed in an upcoming UI refresh.)

**Comment by stefanjudis** [comment]
Haha, I think it's great! Thanks a bunch, Justin!

That does the trick! I'll give it a spin tmrw. And yeah, I don't use the web archive so it's fairly undiscoverable for me. :) 

Have a great weekend!
