### ISSUE TITLE
Have H1 link out to `Newsletter.archive_redirect_url` if set

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#815]

**Comment by Mimort1** [comment]
A quick chaser on this as still outstanding.

**Comment by jmduke** [comment]
Thanks for the ping; I'll get this going this evening.

**Comment by Mimort1** [comment]
Still seems outstanding Justin.

**Comment by ifpingram** [comment]
This only seems to work for Subscribers who are logged in, and not those who are not.

The design of the H1 link on the page differs depending upon whether the subscriber is logged in or not:

Logged in, and the link correctly goes to https://france-insider.com:

<img width="696" alt="Screenshot 2022-08-01 at 19 54 12" src="https://user-images.githubusercontent.com/1426859/182223080-7076a15c-a0ad-4c15-99d1-e5b532024cf9.png">

User not logged in and the link goes to the old archive on https://news.france-insider.com/

<img width="802" alt="Screenshot 2022-08-01 at 19 54 40" src="https://user-images.githubusercontent.com/1426859/182223303-4071301b-fd6b-4b9a-a414-2e2e38930598.png">

Thanks!

**Comment by jmduke** [comment]
Aha, I should have asked for clarification there. Coming live right now.

**Comment by Mimort1** [comment]
Many thanks Justin.
