### ISSUE TITLE
Provide Login Flow

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#823]
We are finding a significant number of our subscribers are not understanding the joint subscription and login flow, which share the same "Subscribe" input field.

These users are familiar with a Subscription flow and then a separate Login flow. 

Is there any way to provide a Separate Login button?

Alternatively, I have been playing with the responses from:

https://news.france-insider.com/api/emails/check-subscriber-email

and so perhaps rather than a separate form, perhaps you could just test a GET parameter sent to an Article, which would auto-login subscribers on that page. Thus, the idea would be like:

1. Subscriber uses our login form.
2. We send a check-subscriber-email request
3. If the user is not Premium / Churning / Gifted we would tell them to upgrade their subscription to login
4. If the user is Premium / Churning / Gifted we would then HTTP redirect them to the page with the GET param, like:

https://news.france-insider.com/archive/wind-turbines-and-french-property-prices?login=user@domain.com

Which would then authenticate and login the user and give them access to the article, in one fell swoop.

This would sort out so many of the daily queries we have to answer from our subscribers.

Thanks!

**Comment by jmduke** [comment]
Two items here:

1. I've actually been mulling over a separate login flow that uses a magic link (hit login, type your email, you get an email that redirects you to the sign in) for this exact reason!  That feels like a good path here.
2. For this second one — Buttondown already has an endpoint that will essentially do this! It's `/subscribers/<subscriber-id>/archive/<slug>`. You should be able to integrate with that.

**Comment by ifpingram** [comment]
Regards the first suggestion, I love magic links myself, but they are still very clever and not necessarily suitable for the (dare I say it) boomer generation. If you can have a very explicit "Login" sign / header, followed by the input for the email address, to start the flow, that would be great. Trying to munge it into the Subscribe field would defeat the object, as it is against the expectation.

I'll give the second suggestion a go now.

**Comment by jmduke** [comment]
Makes sense! Let me try mocking up some stuff this coming week.

**Comment by ifpingram** [comment]
Suggestion number 2 Works really well! Cheers!
