### ISSUE TITLE
Selection count in unsubscribe-confirmation dialog overcounts-by-1 ... after adding a subscriber?

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#830]
Repro:
Go to subscribers list page.
[Do some unknown amount of stuff - I have added 2 new subscribers, applied some tags, haven't unsubbed any]
Select the checkbox next to one subscriber. Act-on-selection toolbar appears, saying "1 selected subscriber"
Click "Unsubscribe" EITHER from the toolbar OR the triple-dot menu on the single subscriber

Expected: Confirmation should say "Unsubscribe 1 subscriber?"
Actual: "Unsubscribe 2 subscribers?"
![image](https://user-images.githubusercontent.com/89615/184444571-ecc912de-96f2-44b5-b603-ce48dd30a804.png)

If two are selected, the dialog says "3" so it appears to be an off-by-one.

REVISION: A full page refresh seemed to reset the selection-count-state. Using the select-all checkbox to select-all, then select-none, did not previously align the selection-count-state. Adding another subscriber afterwards did not screw it up again. I am unsure how to reproduce.

**Comment by jmduke** [comment]
I reproduced this by going into the detail modal for a subscriber, going back to the list view, and _then_ popping up the unsubscribe modal. (There's a cache for the subscriber detail objects that doesn't get cleared out.) Thanks for the flag — pushing a fix now
