### ISSUE TITLE
Authors can now resubscribe subscribers who accidentally unsubscribed

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#858]
I unsubscribed the wrong person.
I want to undo the mistake and resubscribe them.
Expected behavior (or feature request): Safe and easy way to do so

Additional design note:
I select them, then go to the context menu, hoping that there's a "resubscribe" option there:
![image](https://user-images.githubusercontent.com/89615/189512476-2d411335-ce90-4e0b-a6b5-63431eaff712.png)
Not much use in an "Unsubscribe" option on an already-unsubscribed person.

Bug #704 makes me a little more blocked here, because I hesitate to go through the Add-new flow again, creating a duplicate and bifurcating their event history. Is that my only option, though?

**Comment by jmduke** [comment]
Agreed (on both counts). And thanks for the bump on #704 — will take another look on that, it fell off my radar!
