### ISSUE TITLE
Shortened URLs are not accessible right after sending an email

### ISSUE THREAD

**Issue by stefanjudis** [buttondown-email/roadmap#862]
Some folks reached out to me and told me that when they receive the email and click links shortly after, they'll face `ERR_CONNECTION_REFUSED`. Find a screenshot of it below. 👇

<img width="449" alt="image" src="https://user-images.githubusercontent.com/962099/190136339-61a81753-b6bb-4d6a-a26a-2a983de27674.png">

If some time passes, the issue resolves itself and all URLs properly redirect.

No idea how to debug this, but wanted to mention it. ;)

**Comment by jmduke** [comment]
Oh wow, this is...an interesting one, and not one that I've heard before (the tracking, as you might guess, is being handled by AWS so I don't have a huge amount of introspection here). Will look into it.
