### ISSUE TITLE
bug: getting (incorrect?) "unable to save draft" toasts while writing, in conflict with "Draft Saved!" button-status

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#873]
Start writing a new email.
Give it a title. (seems ok)
Start writing in the body.
Expected: everything ok, or at least matching feedback
Actual: error toast after every little bit of editing
Actual: conflicting UI, toast contradicts the "Draft Saved!" status feedback buttony-thing at the bottom of the page

![image](https://user-images.githubusercontent.com/89615/191574875-5bed0cd4-62f2-49a7-b404-b1d488288bb3.png)

the XHR to /api/emails/emails returns a 201 created and the response doesn't seem to contain any error in it, so I think the toast is wrong.

**Comment by james-baker** [comment]
Ohhhh, this ain't lookin' good either (after some more writing):
![image](https://user-images.githubusercontent.com/89615/191576383-1240f799-9f2b-44f2-a19d-56f7d0806e02.png)

**Comment by jmduke** [comment]
(The first issue is a bit of a clientside caching issue for drafts; fix going live right now. Checking out the second one, though...)

**Comment by jmduke** [comment]
Ah yeah, the latter is a painful consequence of the former. Want me to go ahead and nuke all of those for ya?

**Comment by jmduke** [comment]
Woop! Closing this.

> due to no multi-page-select-everything) using the Filter functionality

Just filed [this](https://github.com/buttondown-email/roadmap/issues/874) which is a bit more expansive than just what you're describing, but still.
