### ISSUE TITLE
subscribers type-filtering broken

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#875]
Repro:
Go to https://buttondown.email/subscribers
See that list is labeled "Active Subscribers"

Expected: No rows with status of "Unsubscribed"
Actual: List includes Unsubscribed people

Select "Bounced" or "Spammy" or "Unsubscribers" filter

Expected: List updates to the filter (which looks correct in the URL)
Actual: They all show the same list of everyone

**Comment by jmduke** [comment]
Hmm, is it possible you're on a slightly old cache? Those filters should actually be gone now!:

![CleanShot 2022-09-22 at 17 31 07](https://user-images.githubusercontent.com/461046/191854743-d806cf89-5064-4dee-92dd-99285d00890e.png)

**Comment by jmduke** [comment]
Closing this; LMK if it recurs!

**Comment by james-baker** [comment]
(Oh yeah, my bad, totally a caching issue.)
