### ISSUE TITLE
Allow negative filtering in checkbox parameters

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#884]
Feature request: Would love to be able to use the new filtering widgetry to filter *out* (as well as *in*) tags.

Use case 1: I just sent an email to "everyone with tag A and not tag B" and had to hand-select, luckily it's a small list. (And this could have happened in the email-authoring tag-selection, too, which would have avoided the "send to archive, then send via the subscriber list page" flow I had to figure out for this one.)

Use case 2: I want my default list view to be "all statuses except unsubscribed" which currently means "check every other box". Then if I want to actually filter to a specific status, it's "unselect everything, then select the one I want".

Not sure if the solution is a tri-state checkbox or what.

**Comment by jmduke** [comment]
Ugh, yeah. I think I'll borrow the faux-checkbox from the sending input where you can double click to exclude for this, but it's a hard feature to discover/explain.

**Comment by james-baker** [comment]
Hah wow so it is there. I just discovered the existence of that feature on "the sending input". Was specifically looking for it, didn't find it - and I'm the web dev that implemented checkbox controls for Tableau quickfilters so... yup hard to discover.

Unsolicited design opinion, I'd consider using a small "x" button to the right of the tag names, rather faint until it comes alive when hovered over. When clicked, it would uncheck the box (if previously checked) and put the tag name in strikethrough font, as well as locking the x-button's active state (visually similar to the hover state, maybe with a stronger border).
That would leave the checkbox as a simple checkbox, and be visually discoverable while still pretty unobtrusive.

Complicating factor in the short term: It's currently almost impossible to double-click on the checkboxes in the filter widget. That's because the first click triggers an immediate emptying of the content of the list, which removes the scrollbar from the page, which jerks the filter widget to the right (by the 17px of a standard scrollbar IIRC) enough that the pointer is no longer over the checkbox for a second click.
The jumpy list content is annoying in its own right, so the proper design to keep the filter widget stable there might look like putting the spinner *over* the existing content (along with a mostly-transparent overlay on the list content) while the round-trip happens.

**Comment by jmduke** [comment]
> I'm the web dev that implemented checkbox controls for Tableau quickfilters

I might have to pick your brain on this more, then! (One of the other things I was considering was having the default  state of "all subscriber types / email types" to show up as everything checked rather than nothing checked, btw — but then you run into the problem of it being difficult to quickly filter down to a specific type.)

Jumping to the ending here though:

> The jumpy list content is annoying in its own right, so the proper design to keep the filter widget stable there might look like putting the spinner over the existing content (along with a mostly-transparent overlay on the list content) while the round-trip happens.

Agreed — this is annoying. Gonna bake this out as its [own roadmap item](https://github.com/buttondown-email/roadmap/issues/886).

**Comment by james-baker** [comment]
I almost talked about that (the quick to select-unselect duality) in my last post. :) We ended up with a default==checked plus an "(All)" item for toggling all the checkboxes in a list quickly. I think that "checked means shown" simplicity was well-supported by our users' experience. Not that it fit their pre-existing mental model (most users really had no default model in their heads a priori), but that it was very easy to learn and use for both the "filter to one" and "filter out one" tasks.

And we didn't support the mixing of includes with excludes, we had a separate exclude-mode vs include-mode, which only made sense in the context where the data was categorically independent. (Which tags are not, they can overlap. Thus the "little x on the right" design above is my own personal extension theory.)
