### ISSUE TITLE
Indicate which newsletter is active

### ISSUE THREAD

**Issue by kmikeym** [buttondown-email/roadmap#9]
When a user has multiple newsletters and logs in there is no indication which newsletter is currently active unless they check archives or "switch active newsletter."

Adding some indicator (header?) would prevent user from needing to "switch" newsletters in order to confirm. (In traffic signage this is called a "reassurance or confirming marker").

**Comment by jmduke** [comment]
+1; have this in my (non-GitHub) backlog. This will be showing up in the sidebar. (Note that if you have icons for your newsletters that will show up in the top-right of the application, so that's a bit of a short term fix.)

**Comment by jmduke** [comment]
While this isn't live _yet_, it's going live as part of https://github.com/buttondown-email/roadmap/issues/784 — closing this out in favor of that issue.

![CleanShot 2022-09-01 at 10 35 54](https://user-images.githubusercontent.com/461046/187941079-fa976a2b-1dda-46f1-bbf6-ad203bb03c0c.png)
