### ISSUE TITLE
Allow Creating a Email-Only/Non-Archived Issue

### ISSUE THREAD

**Issue by dstarner** [buttondown-email/roadmap#905]
If a writer makes a mistake in an issue that is sent out, it is possible to edit the published content to the archive page, but it is not possible to update the emails that were sent - obviously.

Instead, as a user, I would like the ability to send either a follow-up email on an issue or send an issue that is selected not to show up in the archive list. This would allow me to send my subscribers a quick revision, fix, or comment about the error without the new message being included in the archive list.

This would allow a writer to handle any typos or mistakes in their newsletter more easily when sending it out to subscribers that might not view the updated content on the website.

### Example Use Case

1. I have the following comment on an issue
   ```
   2 + 2 = 5, everyone knows that!
   ```
2. I send it to my subscribers, and it gets posted to the archive list
3. _Oops!_ I recognize my mistake and promptly update it in the archived version of the email.
   ```
   2 + 2 = 5, everyone knows that!
   ```
   This means it will now show up correctly for people who visit the website version of the issue.
4. 🚨 **FEATURE REQUEST**🚨: I would like to send a new issue and mark it as _Email Only_, with the following contents.
    ```
    You recently received a newsletter issue where I said 2 + 2 = 5, and that's not true; everyone knows 2 + 2 = Fish.
    ```
    This new email would get sent to subscribers, but **would not show up on my archive list**

**Comment by jmduke** [comment]
Totally makes sense. (And love what I assume to be the unintentional mistake of point 3 still referring to `2 + 2 = 5`.)

I think I'd probably model this out as completely differently the actual editing of the archive. Something like a "Add addendum" button that lets you send out an arbitrary addendum to an email that way we can avoid a bunch of edge cases. Makes a lot of sense, though.

**Comment by dstarner** [comment]
> And love what I assume to be the unintentional mistake of point 3 still referring to 2 + 2 = 5.

lol this was supposed to be an actual fix, but I guess that would be _another_ "addendum" as you called it because I copy/pasted too fast.

**Comment by jmduke** [comment]
(This has been implemented as a "private" audience type!)
