### ISSUE TITLE
minor bug: 500 page has broken link

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#908]
I assume you're hot on the trail of the current 503s.
AFTER that's over:

Repro:
hit a 50x error
"head back home" on the 500 error page content is a link
Expected: link goes... somewhere valid, even if one doesn't expect it to be very helpful
Actual: currently links to https://buttondown.s3-us-west-2.amazonaws.com/ which just returns some "Access Denied" XML

Probably because it's just a `<a href="/">` relative link and the static page is https://buttondown.s3-us-west-2.amazonaws.com/static_pages/500.html

**Comment by jmduke** [comment]
The joy of relative links! Thanks for the flag; fix rolling live now.
