### ISSUE TITLE
Drag and drop images broken in Markdown editor

### ISSUE THREAD

**Issue by rghedin** [buttondown-email/roadmap#91]
Hi Justin! I use the Markdown editor and was used to drag and drop images to upload them. Since the editor changed, this isn't working anymore. In fact, there's no way to upload images in Markdown editor (I have to change to the Rich text one to send images).

**Comment by jmduke** [comment]
Ah, I had this listed in https://github.com/buttondown-email/roadmap/issues/79 but no harm breaking it into it's own issue. Should get it resolved soon.

**Comment by jmduke** [comment]
Done!
