### ISSUE TITLE
Uploading image no longer adds image name in Alt Tag

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#911]
When using the new article edit interface to upload an image, the resulting markdown code no longer adds the image filename as the Alt tag (within the square brackets) to render in the image tag in the article publicly.

For instance an image of filename "foobar.jpg" now loads as:

```markdown
![](https://buttondown.s3.us-west-2.amazonaws.com/images/7779232e-dc46-436a-8e50-a0eeb035ad0c.jpg)
```

whereas previously it would load as:

```markdown
![foobar.jpg](https://buttondown.s3.us-west-2.amazonaws.com/images/7779232e-dc46-436a-8e50-a0eeb035ad0c.jpg)
```

Thanks!

**Comment by jmduke** [comment]
This is in Markdown mode, right? I just tried with that exact image and it appeared to work:

![image](https://user-images.githubusercontent.com/461046/199064009-26fa7b4f-d2ef-41dc-a636-a8f70b231e0a.png)

**Comment by ifpingram** [comment]
Yes, when in Markdown mode IIRC.

**Comment by jmduke** [comment]
Got it; thanks. Can repro.
