### ISSUE TITLE
Duplicate emails following edit

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#914]
I am unable to reproduce this myself, as it seems like a flaky bug, but we are seeing that sometimes when a Sent email is edited, instead of updating the email (or perhaps as well as), a new email is inserted into the list of emails. This new email does not seem to have been assigned a "secondary_id", when we return it via the API, thus causing our import to break (which is what alerted me to the bug).

Sorry I can't be more helpful at this time, I will endeavour to reproduce it and post more if I can.

**Comment by jmduke** [comment]
@ifpingram no worries; thanks for the flag. Do you have an example email ID I can look at here?

**Comment by ifpingram** [comment]
I've deleted them now, as I needed to fix our API to load articles. When it
happens again, I will get the ID for you.

Thanks

Ing
