### ISSUE TITLE
missing word in "You sent an email" dialog

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#915]
expected: "it'll be visible"
actual: "it'll visible"

Sentence context: "If it's a public email, it'll visible to everyone at the following URL"

this shows for the minute before sending. After sending, the grammar of "it's visible to" is correct.

**Comment by jmduke** [comment]
I feel like I need to donate $100 to a charity whenever someone spots a copywriting error of this magnitude. (T/Y — fix rolling live.)
