### ISSUE TITLE
inconsistent font size in preview rendering of lists

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#916]
List (ordered or unordered) text is noticeably smaller (in the preview) than regular paragraph text.

I use markdown mode, but it's the same when I switch to wysiwyg mode.
This appears to be a live-preview defect only, as the draft email correctly renders all text the same size.

Repro is any text like this:
```
Paragraph text is bigger

* bullet list text is smaller
* more bullets are all still small

more text goes back to regular size
```

With rendering looking like this:
![image](https://user-images.githubusercontent.com/89615/201242439-d36b3e54-2028-43a2-b052-8d2b082108e3.png)

Analysis: I see this CSS on the p tag, that doesn't seem to have an analogue for the ul or li:
.live-preview p {
    line-height: 24px;
    font-size: 18px;
}

**Comment by benborgers** [comment]
Should be fixed!
