### ISSUE TITLE
Unstructured / extensible external links

### ISSUE THREAD

**Issue by mstenta** [buttondown-email/roadmap#917]
Any plans to add a Mastodon social media URL option? We just set up ours and would love to include it!

**Comment by jmduke** [comment]
Happy to; will get to it either this weekend or early next week.

**Comment by voxdumnonia** [comment]
If we could have something more open-ended and/or extensible, that would be great. There are a lot of services not covered by the hard-coded "Social" links currently available - vimeo, pixelfed, peertube, spotify to name a few as well as mastodon instances (which don't all have the same URL, so need to be more editable). It would be fine if we could just have a description and URL field to fill in and maybe an "add more" button so it doesn't clutter up the setup page with a long list of empty boxes, but just adds them for the ones we've set.

**Comment by jmduke** [comment]
Pretty reasonable, and not difficult to implement (the social links are being stored as a structured hash right now so there’s no real difficulty in spinning up more on the backend). I think I’ll need to do some shenanigans in terms of pulling the favicon to create an icon for each one.

**Comment by jmduke** [comment]
Pushing Mastodon support live right now; leaving this open (and renaming) for the more open-ended side of things that @voxdumnonia mentioned.

**Comment by mstenta** [comment]
Thanks you @jmduke !!
