### ISSUE TITLE
Sent email stuck in "About to send" status

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#919]
We believe that the following email has been sent (was sent over an hour ago), but it seems to still display as "About to send" in the backend:

<img width="1427" alt="Screenshot 2022-11-15 at 15 23 21" src="https://user-images.githubusercontent.com/1426859/201959375-6d509c42-85be-4feb-87bc-770769243ddc.png">

**Comment by Mimort1** [comment]
Problem might have arisen as article pressed to 'Send', which I then cancelled, after which I successfully sent again. It appears to have been received and is appearing on Buttondown. However, not able to upload to our own website as stuck in 'About to Send'.

**Comment by jmduke** [comment]
Oh, interesting — so you sent it, undid the send, and then sent again?

**Comment by Mimort1** [comment]
Correct, but I cancelled before it was actually sent, using option on the card.

**Comment by Mimort1** [comment]
No mails were showing as having been sent before I cancelled. When I then sent, I stayed with the card until I had seen that it had gone out to all recipients. I have also received responses from the mailing, so must have been received.

**Comment by ifpingram** [comment]
It now seems to be showing as "sent". However, there is no publish date, which is causing our API to break, as we need this date for our import.

https://buttondown.email/emails/bee9b4d2-d4e5-4b9a-bb26-a32ceab3394f

Can you please add a date for the 15th Nov (any time is fine), so that we can reload our articles.

Thanks!
