### ISSUE TITLE
off-by-one in post-publish dialog count of emails sent

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#946]
![image](https://user-images.githubusercontent.com/89615/203921851-59039355-dabe-4261-89ba-02f47cc01cf7.png)

They say the two hardest problems in computer science are cache invalidation, naming things, and off-by-one errors. :)

To be specific: the 258/257 fraction seems wrong.
Analysis:
I think the pre-publish said 258.
Aha, analytics says 258 subscribers and 257 delivered. Maybe that's related.
I would expect the numerator to be "emails sent" and the denominator to be subscribers aka "emails expected to be sent" (without delivery status factoring into it, although delivery status would be a cool thing to explicitly highlight in addition)

**Comment by jmduke** [comment]
Ha! This should be easy enough to poke into, but do you mind elaborating on this?:

> (without delivery status factoring into it, although delivery status would be a cool thing to explicitly highlight in addition)

**Comment by james-baker** [comment]
I mean, "emails sent" is just about sending, not their receipt. And. If, after that, there was a parenthetical like "(99.6% delivery success)" that would be a cool bit of information to surface there if it's known at that time.
