### ISSUE TITLE
Urgent: API; listing emails has lost next & previous pagination URLs

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#966]
Hitting the API endpoint for listing emails now no longer returns the URLs for Next or Previous pages:

 GET → https://api.buttondown.email/v1/emails

<img width="236" alt="Screenshot 2022-12-06 at 10 32 58" src="https://user-images.githubusercontent.com/1426859/205887809-b436d001-8917-497a-a9b7-90ef2a30329b.png">

Without this we are unable to paginate, and can only load the articles up until the 1st July 2022:

https://france-insider.com/

**Comment by jmduke** [comment]
🤦 Should have had a contract test for this (pagination itself still works, but I didn't realize the new pagination construct removed those pointers.) Pushing a fix now, sorry about that.

**Comment by ifpingram** [comment]
Thanks!
