### ISSUE TITLE
Improve header of bulk action modal

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#972]
> When I go to delete a draft, it asks “Delete <UUID here>?” rather than the newsletter name. This makes it scary to delete things.

**Comment by chadwhitacre** [comment]
Seeing this for subscriber deletion as well, I get the UUID instead of the name. Agree scary to delete!

<img width="602" alt="Screen Shot 2023-01-26 at 3 43 55 PM" src="https://user-images.githubusercontent.com/134455/214946448-ca45660d-4207-4b27-9a70-f7b1df916008.png">

**Comment by jmduke** [comment]
Done!

**Comment by chadwhitacre** [comment]
Confirmed, thanks!

<img width="613" alt="Screen Shot 2023-02-05 at 8 49 50 PM" src="https://user-images.githubusercontent.com/134455/216863649-9ea4844a-3421-4b51-9989-47cda9ee7cad.png">
