### ISSUE TITLE
Add documentation on the difference between using tags and using separate newsletters

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#999]
This is a fairly common question: people want to segment their stuff _somehow_, but don't know which is the right route. (I write about Python and I write about Webdev and I have people who want either one or both, which should I use?) The TL;DR is —

1. Multiple newsletters mean separated archives
2. Subscribers can opt out of separate newsletters but can't opt out of their tags
3. You can send to interesting combinations of tags but you can't easily send an email across multiple newsletters

**Comment by benborgers** [comment]
Added here! https://docs.buttondown.email/advanced-features/tags-vs-newsletters
